import { Word, CEFRLevel } from '../types';
import { saveCefrLevelOffline, getCefrLevelOffline, CEFR_DATABASE_VERSION } from './offlineSyncService';

export interface CefrLevelMeta {
  level: CEFRLevel;
  nameUz: string;
  nameEn: string;
  count: number;
  topicCount: number;
  ieltsBand: string;
  cefrColor: string;
  gradient: string;
  description: string;
  focus: string;
}

export const CEFR_LEVELS_META: Record<CEFRLevel, CefrLevelMeta> = {
  A1: {
    level: 'A1',
    nameUz: 'Boshlang‘ich (Beginner)',
    nameEn: 'Beginner',
    count: 1500,
    topicCount: 14,
    ieltsBand: '2.0 – 3.0',
    cefrColor: 'emerald',
    gradient: 'from-emerald-500 to-teal-600',
    description: 'Kundalik eng zarur so‘zlar, salomlashuv, raqamlar, oila va sodda iboralar.',
    focus: 'Kundalik muloqot va asosiy tushunchalar',
  },
  A2: {
    level: 'A2',
    nameUz: 'Elementar (Elementary)',
    nameEn: 'Elementary',
    count: 1500,
    topicCount: 16,
    ieltsBand: '3.5 – 4.0',
    cefrColor: 'teal',
    gradient: 'from-teal-500 to-cyan-600',
    description: 'Do‘kon, sayohat, ish, uy-joy va o‘tgan zamon voqealari haqida suhbatlashish.',
    focus: 'Kundalik vaziyatlar va shaxsiy ma’lumotlar',
  },
  B1: {
    level: 'B1',
    nameUz: 'O‘rta (Intermediate)',
    nameEn: 'Intermediate',
    count: 2000,
    topicCount: 41,
    ieltsBand: '4.5 – 5.0',
    cefrColor: 'blue',
    gradient: 'from-blue-500 to-indigo-600',
    description: 'O‘z fikrini ifodalash, orzular, tajribalar va kundalik mavzularda mustaqil suhbat.',
    focus: 'Erkin ifoda va ijtimoiy muloqot',
  },
  B2: {
    level: 'B2',
    nameUz: 'Yuqori o‘rta (Upper-Intermediate)',
    nameEn: 'Upper-Intermediate',
    count: 2500,
    topicCount: 39,
    ieltsBand: '5.5 – 6.5',
    cefrColor: 'indigo',
    gradient: 'from-indigo-600 to-purple-600',
    description: 'Murakkab matnlar, abstrakt tushunchalar, munozara va professional soha so‘zlari.',
    focus: 'Professional va akademik tayyorgarlik',
  },
  C1: {
    level: 'C1',
    nameUz: 'Ilg‘or (Advanced)',
    nameEn: 'Advanced',
    count: 1500,
    topicCount: 21,
    ieltsBand: '7.0 – 8.0',
    cefrColor: 'purple',
    gradient: 'from-purple-600 to-pink-600',
    description: 'Akademik ilmiy matnlar, yashirin ma’nolar, boy sinonimlar va ravon nutq.',
    focus: 'IELTS 7.5+ va professional mutaxassislik',
  },
  C2: {
    level: 'C2',
    nameUz: 'Mukammal (Proficiency)',
    nameEn: 'Proficiency',
    count: 1000,
    topicCount: 19,
    ieltsBand: '8.5 – 9.0',
    cefrColor: 'amber',
    gradient: 'from-amber-500 to-rose-600',
    description: 'Ona tili darajasidagi boy lug‘at, nozik ma’nodosh so‘zlar, adabiy va ilmiy terminlar.',
    focus: 'To‘liq ona tili darajasi va akademik mukammallik',
  },
};

export interface CefrTopicMeta {
  category: string;
  nameUz: string;
  nameEn: string;
  emoji: string;
  color: string;
  gradient: string;
  bgLight: string;
  borderLight: string;
  textAccent: string;
  description: string;
}

export const CEFR_TOPIC_CATEGORIES: Record<string, CefrTopicMeta> = {
  "Salomlashuv va Kundalik muloqot": {
    category: "Salomlashuv va Kundalik muloqot",
    nameUz: "Salomlashuv va Kundalik muloqot",
    nameEn: "Greetings & Basic Communication",
    emoji: "💬",
    color: "blue",
    gradient: "from-blue-600 to-indigo-700",
    bgLight: "bg-blue-50/80",
    borderLight: "border-blue-200",
    textAccent: "text-blue-800",
    description: "Kundalik salomlashuv, minnatdorchilik, xushmuomalalik iboralari va oddiy suhbat so‘zlari.",
  },
  "Greetings & Basic Communication": {
    category: "Salomlashuv va Kundalik muloqot",
    nameUz: "Salomlashuv va Kundalik muloqot",
    nameEn: "Greetings & Basic Communication",
    emoji: "💬",
    color: "blue",
    gradient: "from-blue-600 to-indigo-700",
    bgLight: "bg-blue-50/80",
    borderLight: "border-blue-200",
    textAccent: "text-blue-800",
    description: "Kundalik salomlashuv, minnatdorchilik, xushmuomalalik iboralari va oddiy suhbat so‘zlari.",
  },
  "Joylar, Transport va Sayohat": {
    category: "Joylar, Transport va Sayohat",
    nameUz: "Joylar, Transport va Sayohat",
    nameEn: "Places, Transport & Travel",
    emoji: "🚆",
    color: "sky",
    gradient: "from-sky-500 to-blue-600",
    bgLight: "bg-sky-50/80",
    borderLight: "border-sky-200",
    textAccent: "text-sky-800",
    description: "Shahar joylari, bekatlar, aeroport, transport turlari va sayohatdagi eng zarur so‘zlar.",
  },
  "Places, Transport & Travel": {
    category: "Joylar, Transport va Sayohat",
    nameUz: "Joylar, Transport va Sayohat",
    nameEn: "Places, Transport & Travel",
    emoji: "🚆",
    color: "sky",
    gradient: "from-sky-500 to-blue-600",
    bgLight: "bg-sky-50/80",
    borderLight: "border-sky-200",
    textAccent: "text-sky-800",
    description: "Shahar joylari, bekatlar, aeroport, transport turlari va sayohatdagi eng zarur so‘zlar.",
  },
  "Tabiat, Hayvonlar va Ob-havo": {
    category: "Tabiat, Hayvonlar va Ob-havo",
    nameUz: "Tabiat, Hayvonlar va Ob-havo",
    nameEn: "Nature, Animals & Weather",
    emoji: "🌿",
    color: "emerald",
    gradient: "from-emerald-500 to-teal-600",
    bgLight: "bg-emerald-50/80",
    borderLight: "border-emerald-200",
    textAccent: "text-emerald-800",
    description: "Hayvonot olami, o‘simliklar, fasllar, ob-havo holatlari va atrof-muhit so‘zlari.",
  },
  "Nature, Animals & Weather": {
    category: "Tabiat, Hayvonlar va Ob-havo",
    nameUz: "Tabiat, Hayvonlar va Ob-havo",
    nameEn: "Nature, Animals & Weather",
    emoji: "🌿",
    color: "emerald",
    gradient: "from-emerald-500 to-teal-600",
    bgLight: "bg-emerald-50/80",
    borderLight: "border-emerald-200",
    textAccent: "text-emerald-800",
    description: "Hayvonot olami, o‘simliklar, fasllar, ob-havo holatlari va atrof-muhit so‘zlari.",
  },
  "Kundalik Harakat Fe’llari": {
    category: "Kundalik Harakat Fe’llari",
    nameUz: "Kundalik Harakat Fe’llari",
    nameEn: "Everyday Verbs",
    emoji: "⚡",
    color: "amber",
    gradient: "from-amber-500 to-orange-600",
    bgLight: "bg-amber-50/80",
    borderLight: "border-amber-200",
    textAccent: "text-amber-800",
    description: "Kundalik hayotda eng ko‘p qo‘llaniladigan asosiy fe’llar va harakat tushunchalari.",
  },
  "Everyday Verbs": {
    category: "Kundalik Harakat Fe’llari",
    nameUz: "Kundalik Harakat Fe’llari",
    nameEn: "Everyday Verbs",
    emoji: "⚡",
    color: "amber",
    gradient: "from-amber-500 to-orange-600",
    bgLight: "bg-amber-50/80",
    borderLight: "border-amber-200",
    textAccent: "text-amber-800",
    description: "Kundalik hayotda eng ko‘p qo‘llaniladigan asosiy fe’llar va harakat tushunchalari.",
  },
  "Asosiy Sifatlar va Hissiyotlar": {
    category: "Asosiy Sifatlar va Hissiyotlar",
    nameUz: "Asosiy Sifatlar va Hissiyotlar",
    nameEn: "Common Adjectives & Feelings",
    emoji: "✨",
    color: "purple",
    gradient: "from-purple-500 to-indigo-600",
    bgLight: "bg-purple-50/80",
    borderLight: "border-purple-200",
    textAccent: "text-purple-800",
    description: "Narsalarni tasvirlovchi sifatlar, kayfiyat va insoniy his-tuyg‘ular.",
  },
  "Common Adjectives & Feelings": {
    category: "Asosiy Sifatlar va Hissiyotlar",
    nameUz: "Asosiy Sifatlar va Hissiyotlar",
    nameEn: "Common Adjectives & Feelings",
    emoji: "✨",
    color: "purple",
    gradient: "from-purple-500 to-indigo-600",
    bgLight: "bg-purple-50/80",
    borderLight: "border-purple-200",
    textAccent: "text-purple-800",
    description: "Narsalarni tasvirlovchi sifatlar, kayfiyat va insoniy his-tuyg‘ular.",
  },
  "Asosiy Grammatik So‘zlar": {
    category: "Asosiy Grammatik So‘zlar",
    nameUz: "Asosiy Grammatik So‘zlar",
    nameEn: "Basic Grammar Words",
    emoji: "🧩",
    color: "indigo",
    gradient: "from-indigo-500 to-violet-600",
    bgLight: "bg-indigo-50/80",
    borderLight: "border-indigo-200",
    textAccent: "text-indigo-800",
    description: "Predloglar, bog‘lovchilar, olmoshlar va gap qurilishi uchun zarur yordamchi so‘zlar.",
  },
  "Basic Grammar Words": {
    category: "Asosiy Grammatik So‘zlar",
    nameUz: "Asosiy Grammatik So‘zlar",
    nameEn: "Basic Grammar Words",
    emoji: "🧩",
    color: "indigo",
    gradient: "from-indigo-500 to-violet-600",
    bgLight: "bg-indigo-50/80",
    borderLight: "border-indigo-200",
    textAccent: "text-indigo-800",
    description: "Predloglar, bog‘lovchilar, olmoshlar va gap qurilishi uchun zarur yordamchi so‘zlar.",
  },
  "Odamlar va Oila": {
    category: "Odamlar va Oila",
    nameUz: "Odamlar va Oila",
    nameEn: "People & Family",
    emoji: "👨‍👩‍👧",
    color: "rose",
    gradient: "from-rose-500 to-pink-600",
    bgLight: "bg-rose-50/80",
    borderLight: "border-rose-200",
    textAccent: "text-rose-800",
    description: "Oila a’zolari, qarindoshlik aloqalari, do‘stlar va insoniy munosabatlar.",
  },
  "People & Family": {
    category: "Odamlar va Oila",
    nameUz: "Odamlar va Oila",
    nameEn: "People & Family",
    emoji: "👨‍👩‍👧",
    color: "rose",
    gradient: "from-rose-500 to-pink-600",
    bgLight: "bg-rose-50/80",
    borderLight: "border-rose-200",
    textAccent: "text-rose-800",
    description: "Oila a’zolari, qarindoshlik aloqalari, do‘stlar va insoniy munosabatlar.",
  },
  "Shaxsiy Ma’lumotlar": {
    category: "Shaxsiy Ma’lumotlar",
    nameUz: "Shaxsiy Ma’lumotlar",
    nameEn: "Personal Information",
    emoji: "🪪",
    color: "teal",
    gradient: "from-teal-500 to-emerald-600",
    bgLight: "bg-teal-50/80",
    borderLight: "border-teal-200",
    textAccent: "text-teal-800",
    description: "Ism-familiya, yosh, manzil, telefon, millat va anketalarni to‘ldirish leksikasi.",
  },
  "Personal Information": {
    category: "Shaxsiy Ma’lumotlar",
    nameUz: "Shaxsiy Ma’lumotlar",
    nameEn: "Personal Information",
    emoji: "🪪",
    color: "teal",
    gradient: "from-teal-500 to-emerald-600",
    bgLight: "bg-teal-50/80",
    borderLight: "border-teal-200",
    textAccent: "text-teal-800",
    description: "Ism-familiya, yosh, manzil, telefon, millat va anketalarni to‘ldirish leksikasi.",
  },
  "Raqamlar, Vaqt va Taqvim": {
    category: "Raqamlar, Vaqt va Taqvim",
    nameUz: "Raqamlar, Vaqt va Taqvim",
    nameEn: "Numbers, Time & Calendar",
    emoji: "⏰",
    color: "cyan",
    gradient: "from-cyan-500 to-blue-600",
    bgLight: "bg-cyan-50/80",
    borderLight: "border-cyan-200",
    textAccent: "text-cyan-800",
    description: "Hafta kunlari, oylar, soat vaqtini aytish, sanalar va asosiy hisob-kitob sonlari.",
  },
  "Numbers, Time & Calendar": {
    category: "Raqamlar, Vaqt va Taqvim",
    nameUz: "Raqamlar, Vaqt va Taqvim",
    nameEn: "Numbers, Time & Calendar",
    emoji: "⏰",
    color: "cyan",
    gradient: "from-cyan-500 to-blue-600",
    bgLight: "bg-cyan-50/80",
    borderLight: "border-cyan-200",
    textAccent: "text-cyan-800",
    description: "Hafta kunlari, oylar, soat vaqtini aytish, sanalar va asosiy hisob-kitob sonlari.",
  },
  "Uy va Mebel Jihozlari": {
    category: "Uy va Mebel Jihozlari",
    nameUz: "Uy va Mebel Jihozlari",
    nameEn: "Home & Furniture",
    emoji: "🏠",
    color: "orange",
    gradient: "from-orange-500 to-amber-600",
    bgLight: "bg-orange-50/80",
    borderLight: "border-orange-200",
    textAccent: "text-orange-800",
    description: "Xonalar, mebellar, oshxona va uy jihozlari, maishiy buyumlar nomlari.",
  },
  "Home & Furniture": {
    category: "Uy va Mebel Jihozlari",
    nameUz: "Uy va Mebel Jihozlari",
    nameEn: "Home & Furniture",
    emoji: "🏠",
    color: "orange",
    gradient: "from-orange-500 to-amber-600",
    bgLight: "bg-orange-50/80",
    borderLight: "border-orange-200",
    textAccent: "text-orange-800",
    description: "Xonalar, mebellar, oshxona va uy jihozlari, maishiy buyumlar nomlari.",
  },
  "Oziq-ovqat va Ichimliklar": {
    category: "Oziq-ovqat va Ichimliklar",
    nameUz: "Oziq-ovqat va Ichimliklar",
    nameEn: "Food & Drinks",
    emoji: "🥗",
    color: "emerald",
    gradient: "from-emerald-500 to-green-600",
    bgLight: "bg-emerald-50/80",
    borderLight: "border-emerald-200",
    textAccent: "text-emerald-800",
    description: "Taomlar, mevalar, sabzavotlar, ichimliklar va nonushta/tushlik leksikasi.",
  },
  "Food & Drinks": {
    category: "Oziq-ovqat va Ichimliklar",
    nameUz: "Oziq-ovqat va Ichimliklar",
    nameEn: "Food & Drinks",
    emoji: "🥗",
    color: "emerald",
    gradient: "from-emerald-500 to-green-600",
    bgLight: "bg-emerald-50/80",
    borderLight: "border-emerald-200",
    textAccent: "text-emerald-800",
    description: "Taomlar, mevalar, sabzavotlar, ichimliklar va nonushta/tushlik leksikasi.",
  },
  "Maktab va Ta’lim": {
    category: "Maktab va Ta’lim",
    nameUz: "Maktab va Ta’lim",
    nameEn: "School & Education",
    emoji: "🎓",
    color: "blue",
    gradient: "from-blue-600 to-indigo-700",
    bgLight: "bg-blue-50/80",
    borderLight: "border-blue-200",
    textAccent: "text-blue-800",
    description: "Maktab fanlari, o‘quv qurollari, darslar, imtihonlar va o‘qish jarayoni.",
  },
  "School & Education": {
    category: "Maktab va Ta’lim",
    nameUz: "Maktab va Ta’lim",
    nameEn: "School & Education",
    emoji: "🎓",
    color: "blue",
    gradient: "from-blue-600 to-indigo-700",
    bgLight: "bg-blue-50/80",
    borderLight: "border-blue-200",
    textAccent: "text-blue-800",
    description: "Maktab fanlari, o‘quv qurollari, darslar, imtihonlar va o‘qish jarayoni.",
  },
  "Kiyim-kechak va Tashqi ko‘rinish": {
    category: "Kiyim-kechak va Tashqi ko‘rinish",
    nameUz: "Kiyim-kechak va Tashqi ko‘rinish",
    nameEn: "Clothes & Appearance",
    emoji: "👗",
    color: "pink",
    gradient: "from-pink-500 to-rose-600",
    bgLight: "bg-pink-50/80",
    borderLight: "border-pink-200",
    textAccent: "text-pink-800",
    description: "Ust-bosh kiyimlari, poyabzal, ranglar, uslub va inson tashqi qiyofasi.",
  },
  "Clothes & Appearance": {
    category: "Kiyim-kechak va Tashqi ko‘rinish",
    nameUz: "Kiyim-kechak va Tashqi ko‘rinish",
    nameEn: "Clothes & Appearance",
    emoji: "👗",
    color: "pink",
    gradient: "from-pink-500 to-rose-600",
    bgLight: "bg-pink-50/80",
    borderLight: "border-pink-200",
    textAccent: "text-pink-800",
    description: "Ust-bosh kiyimlari, poyabzal, ranglar, uslub va inson tashqi qiyofasi.",
  },
  "Tana a’zolari va Salomatlik": {
    category: "Tana a’zolari va Salomatlik",
    nameUz: "Tana a’zolari va Salomatlik",
    nameEn: "Body & Health",
    emoji: "🏥",
    color: "red",
    gradient: "from-red-500 to-rose-600",
    bgLight: "bg-red-50/80",
    borderLight: "border-red-200",
    textAccent: "text-red-800",
    description: "Inson tana a’zolari, o‘zini his qilish, oddiy kasalliklar va dorixonadagi so‘zlar.",
  },
  "Body & Health": {
    category: "Tana a’zolari va Salomatlik",
    nameUz: "Tana a’zolari va Salomatlik",
    nameEn: "Body & Health",
    emoji: "🏥",
    color: "red",
    gradient: "from-red-500 to-rose-600",
    bgLight: "bg-red-50/80",
    borderLight: "border-red-200",
    textAccent: "text-red-800",
    description: "Inson tana a’zolari, o‘zini his qilish, oddiy kasalliklar va dorixonadagi so‘zlar.",
  },
  "Sayohat va Transport": {
    category: "Sayohat va Transport",
    nameUz: "Sayohat va Transport",
    nameEn: "Travel & Transport",
    emoji: "✈️",
    color: "sky",
    gradient: "from-sky-500 to-blue-600",
    bgLight: "bg-sky-50/80",
    borderLight: "border-sky-200",
    textAccent: "text-sky-800",
    description: "Chipta bron qilish, aeroport va vokal, parvoz va shahar transporti.",
  },
  "Travel & Transport": {
    category: "Sayohat va Transport",
    nameUz: "Sayohat va Transport",
    nameEn: "Travel & Transport",
    emoji: "✈️",
    color: "sky",
    gradient: "from-sky-500 to-blue-600",
    bgLight: "bg-sky-50/80",
    borderLight: "border-sky-200",
    textAccent: "text-sky-800",
    description: "Chipta bron qilish, aeroport va vokal, parvoz va shahar transporti.",
  },
  "Ish va Karyera": {
    category: "Ish va Karyera",
    nameUz: "Ish va Karyera",
    nameEn: "Work & Career",
    emoji: "💼",
    color: "indigo",
    gradient: "from-indigo-600 to-blue-700",
    bgLight: "bg-indigo-50/80",
    borderLight: "border-indigo-200",
    textAccent: "text-indigo-800",
    description: "Kasbiy faoliyat, ish suhbati, maosh, ofis va mehnat munosabatlari.",
  },
  "Work & Career": {
    category: "Ish va Karyera",
    nameUz: "Ish va Karyera",
    nameEn: "Work & Career",
    emoji: "💼",
    color: "indigo",
    gradient: "from-indigo-600 to-blue-700",
    bgLight: "bg-indigo-50/80",
    borderLight: "border-indigo-200",
    textAccent: "text-indigo-800",
    description: "Kasbiy faoliyat, ish suhbati, maosh, ofis va mehnat munosabatlari.",
  },
  "Tabiat va Atrof-muhit": {
    category: "Tabiat va Atrof-muhit",
    nameUz: "Tabiat va Atrof-muhit",
    nameEn: "Nature & Environment",
    emoji: "🌳",
    color: "emerald",
    gradient: "from-emerald-500 to-teal-600",
    bgLight: "bg-emerald-50/80",
    borderLight: "border-emerald-200",
    textAccent: "text-emerald-800",
    description: "Ekologiya, iqlim o‘zgarishi, tabiiy resurslar va tabiatni asrash.",
  },
  "Nature & Environment": {
    category: "Tabiat va Atrof-muhit",
    nameUz: "Tabiat va Atrof-muhit",
    nameEn: "Nature & Environment",
    emoji: "🌳",
    color: "emerald",
    gradient: "from-emerald-500 to-teal-600",
    bgLight: "bg-emerald-50/80",
    borderLight: "border-emerald-200",
    textAccent: "text-emerald-800",
    description: "Ekologiya, iqlim o‘zgarishi, tabiiy resurslar va tabiatni asrash.",
  },
  "Hissiyotlar va Munosabatlar": {
    category: "Hissiyotlar va Munosabatlar",
    nameUz: "Hissiyotlar va Munosabatlar",
    nameEn: "Emotions & Relationships",
    emoji: "❤️",
    color: "rose",
    gradient: "from-rose-500 to-pink-600",
    bgLight: "bg-rose-50/80",
    borderLight: "border-rose-200",
    textAccent: "text-rose-800",
    description: "Insoniy munosabatlar, empatiya, ishonch, mehr va ruhiy holatlar.",
  },
  "Emotions & Relationships": {
    category: "Hissiyotlar va Munosabatlar",
    nameUz: "Hissiyotlar va Munosabatlar",
    nameEn: "Emotions & Relationships",
    emoji: "❤️",
    color: "rose",
    gradient: "from-rose-500 to-pink-600",
    bgLight: "bg-rose-50/80",
    borderLight: "border-rose-200",
    textAccent: "text-rose-800",
    description: "Insoniy munosabatlar, empatiya, ishonch, mehr va ruhiy holatlar.",
  },
  "Frazali Fe’llar va Iboralar": {
    category: "Frazali Fe’llar va Iboralar",
    nameUz: "Frazali Fe’llar va Iboralar",
    nameEn: "Phrasal Verbs & Expressions",
    emoji: "🔄",
    color: "violet",
    gradient: "from-violet-500 to-purple-600",
    bgLight: "bg-violet-50/80",
    borderLight: "border-violet-200",
    textAccent: "text-violet-800",
    description: "Ingliz tilidagi eng ko‘p qo‘llaniladigan frazali fe’llar va turg‘un birikmalar.",
  },
  "Phrasal Verbs & Expressions": {
    category: "Frazali Fe’llar va Iboralar",
    nameUz: "Frazali Fe’llar va Iboralar",
    nameEn: "Phrasal Verbs & Expressions",
    emoji: "🔄",
    color: "violet",
    gradient: "from-violet-500 to-purple-600",
    bgLight: "bg-violet-50/80",
    borderLight: "border-violet-200",
    textAccent: "text-violet-800",
    description: "Ingliz tilidagi eng ko‘p qo‘llaniladigan frazali fe’llar va turg‘un birikmalar.",
  },
  "Sifatlar va Fikr-mulohazalar": {
    category: "Sifatlar va Fikr-mulohazalar",
    nameUz: "Sifatlar va Fikr-mulohazalar",
    nameEn: "Adjectives & Opinions",
    emoji: "💡",
    color: "amber",
    gradient: "from-amber-500 to-yellow-600",
    bgLight: "bg-amber-50/80",
    borderLight: "border-amber-200",
    textAccent: "text-amber-800",
    description: "O‘z fikrini asoslash, tavsiflash va baholash uchun zarur sifatlar.",
  },
  "Adjectives & Opinions": {
    category: "Sifatlar va Fikr-mulohazalar",
    nameUz: "Sifatlar va Fikr-mulohazalar",
    nameEn: "Adjectives & Opinions",
    emoji: "💡",
    color: "amber",
    gradient: "from-amber-500 to-yellow-600",
    bgLight: "bg-amber-50/80",
    borderLight: "border-amber-200",
    textAccent: "text-amber-800",
    description: "O‘z fikrini asoslash, tavsiflash va baholash uchun zarur sifatlar.",
  },
  "Grammatika va Bog‘lovchilar": {
    category: "Grammatika va Bog‘lovchilar",
    nameUz: "Grammatika va Bog‘lovchilar",
    nameEn: "Grammar & Connectors",
    emoji: "🔗",
    color: "slate",
    gradient: "from-slate-600 to-stone-700",
    bgLight: "bg-slate-50/80",
    borderLight: "border-slate-200",
    textAccent: "text-slate-800",
    description: "Fikrni mantiqiy bog‘lash, sabab-oqibat va zidlovchi bog‘lovchilar.",
  },
  "Grammar & Connectors": {
    category: "Grammatika va Bog‘lovchilar",
    nameUz: "Grammatika va Bog‘lovchilar",
    nameEn: "Grammar & Connectors",
    emoji: "🔗",
    color: "slate",
    gradient: "from-slate-600 to-stone-700",
    bgLight: "bg-slate-50/80",
    borderLight: "border-slate-200",
    textAccent: "text-slate-800",
    description: "Fikrni mantiqiy bog‘lash, sabab-oqibat va zidlovchi bog‘lovchilar.",
  },
  "Xarid va Moliya": {
    category: "Xarid va Moliya",
    nameUz: "Xarid va Moliya",
    nameEn: "Shopping & Money",
    emoji: "💳",
    color: "emerald",
    gradient: "from-emerald-500 to-teal-600",
    bgLight: "bg-emerald-50/80",
    borderLight: "border-emerald-200",
    textAccent: "text-emerald-800",
    description: "Bozor, do‘kon, chegirmalar, bank, to‘lovlar va pul hisob-kitoblari.",
  },
  "Shopping & Money": {
    category: "Xarid va Moliya",
    nameUz: "Xarid va Moliya",
    nameEn: "Shopping & Money",
    emoji: "💳",
    color: "emerald",
    gradient: "from-emerald-500 to-teal-600",
    bgLight: "bg-emerald-50/80",
    borderLight: "border-emerald-200",
    textAccent: "text-emerald-800",
    description: "Bozor, do‘kon, chegirmalar, bank, to‘lovlar va pul hisob-kitoblari.",
  },
  "Sport va Qiziqishlar": {
    category: "Sport va Qiziqishlar",
    nameUz: "Sport va Qiziqishlar",
    nameEn: "Sports & Hobbies",
    emoji: "⚽",
    color: "green",
    gradient: "from-green-500 to-emerald-600",
    bgLight: "bg-green-50/80",
    borderLight: "border-green-200",
    textAccent: "text-green-800",
    description: "Sport turlari, mashg‘ulotlar, musobaqalar va sevimli xobbilar.",
  },
  "Sports & Hobbies": {
    category: "Sport va Qiziqishlar",
    nameUz: "Sport va Qiziqishlar",
    nameEn: "Sports & Hobbies",
    emoji: "⚽",
    color: "green",
    gradient: "from-green-500 to-emerald-600",
    bgLight: "bg-green-50/80",
    borderLight: "border-green-200",
    textAccent: "text-green-800",
    description: "Sport turlari, mashg‘ulotlar, musobaqalar va sevimli xobbilar.",
  },
  "Texnologiya va OAV": {
    category: "Texnologiya va OAV",
    nameUz: "Texnologiya va OAV",
    nameEn: "Technology & Media",
    emoji: "📱",
    color: "cyan",
    gradient: "from-cyan-500 to-blue-600",
    bgLight: "bg-cyan-50/80",
    borderLight: "border-cyan-200",
    textAccent: "text-cyan-800",
    description: "Smartfonlar, internet, ijtimoiy tarmoqlar, dasturlar va axborot texnologiyalari.",
  },
  "Technology & Media": {
    category: "Texnologiya va OAV",
    nameUz: "Texnologiya va OAV",
    nameEn: "Technology & Media",
    emoji: "📱",
    color: "cyan",
    gradient: "from-cyan-500 to-blue-600",
    bgLight: "bg-cyan-50/80",
    borderLight: "border-cyan-200",
    textAccent: "text-cyan-800",
    description: "Smartfonlar, internet, ijtimoiy tarmoqlar, dasturlar va axborot texnologiyalari.",
  },
  "Jamiyat va Muloqot": {
    category: "Jamiyat va Muloqot",
    nameUz: "Jamiyat va Muloqot",
    nameEn: "Society & Communication",
    emoji: "👥",
    color: "blue",
    gradient: "from-blue-600 to-indigo-700",
    bgLight: "bg-blue-50/80",
    borderLight: "border-blue-200",
    textAccent: "text-blue-800",
    description: "Jamiyat hayoti, qonun-qoidalar, madaniy xilma-xillik va ijtimoiy muloqot.",
  },
  "Society & Communication": {
    category: "Jamiyat va Muloqot",
    nameUz: "Jamiyat va Muloqot",
    nameEn: "Society & Communication",
    emoji: "👥",
    color: "blue",
    gradient: "from-blue-600 to-indigo-700",
    bgLight: "bg-blue-50/80",
    borderLight: "border-blue-200",
    textAccent: "text-blue-800",
    description: "Jamiyat hayoti, qonun-qoidalar, madaniy xilma-xillik va ijtimoiy muloqot.",
  },
  "Sayohat va Madaniyat": {
    category: "Sayohat va Madaniyat",
    nameUz: "Sayohat va Madaniyat",
    nameEn: "Travel & Culture",
    emoji: "🏛️",
    color: "teal",
    gradient: "from-teal-500 to-cyan-600",
    bgLight: "bg-teal-50/80",
    borderLight: "border-teal-200",
    textAccent: "text-teal-800",
    description: "Madaniy meros, diqqatga sazovor joylar, urf-odatlar va sayyohlik.",
  },
  "Travel & Culture": {
    category: "Sayohat va Madaniyat",
    nameUz: "Sayohat va Madaniyat",
    nameEn: "Travel & Culture",
    emoji: "🏛️",
    color: "teal",
    gradient: "from-teal-500 to-cyan-600",
    bgLight: "bg-teal-50/80",
    borderLight: "border-teal-200",
    textAccent: "text-teal-800",
    description: "Madaniy meros, diqqatga sazovor joylar, urf-odatlar va sayyohlik.",
  },
  "Kun tartibi va Odatlar": {
    category: "Kun tartibi va Odatlar",
    nameUz: "Kun tartibi va Odatlar",
    nameEn: "Daily Routine & Habits",
    emoji: "📅",
    color: "amber",
    gradient: "from-amber-500 to-orange-600",
    bgLight: "bg-amber-50/80",
    borderLight: "border-amber-200",
    textAccent: "text-amber-800",
    description: "Ertalabdan kechgacha qilinadigan ishlar, odatlar va vaqtni boshqarish.",
  },
  "Daily Routine & Habits": {
    category: "Kun tartibi va Odatlar",
    nameUz: "Kun tartibi va Odatlar",
    nameEn: "Daily Routine & Habits",
    emoji: "📅",
    color: "amber",
    gradient: "from-amber-500 to-orange-600",
    bgLight: "bg-amber-50/80",
    borderLight: "border-amber-200",
    textAccent: "text-amber-800",
    description: "Ertalabdan kechgacha qilinadigan ishlar, odatlar va vaqtni boshqarish.",
  },
  "Salomatlik va Turmush tarzi": {
    category: "Salomatlik va Turmush tarzi",
    nameUz: "Salomatlik va Turmush tarzi",
    nameEn: "Health & Lifestyle",
    emoji: "🍎",
    color: "rose",
    gradient: "from-rose-500 to-red-600",
    bgLight: "bg-rose-50/80",
    borderLight: "border-rose-200",
    textAccent: "text-rose-800",
    description: "Sog‘lom turmush tarzi, fitnes, to‘g‘ri ovqatlanish va tibbiy maslahatlar.",
  },
  "Health & Lifestyle": {
    category: "Salomatlik va Turmush tarzi",
    nameUz: "Salomatlik va Turmush tarzi",
    nameEn: "Health & Lifestyle",
    emoji: "🍎",
    color: "rose",
    gradient: "from-rose-500 to-red-600",
    bgLight: "bg-rose-50/80",
    borderLight: "border-rose-200",
    textAccent: "text-rose-800",
    description: "Sog‘lom turmush tarzi, fitnes, to‘g‘ri ovqatlanish va tibbiy maslahatlar.",
  },
  "Oziq-ovqat va Pazandachilik": {
    category: "Oziq-ovqat va Pazandachilik",
    nameUz: "Oziq-ovqat va Pazandachilik",
    nameEn: "Food & Cooking",
    emoji: "🍳",
    color: "orange",
    gradient: "from-orange-500 to-amber-600",
    bgLight: "bg-orange-50/80",
    borderLight: "border-orange-200",
    textAccent: "text-orange-800",
    description: "Retseptlar, taom tayyorlash usullari, pazandachilik va oshxona anjomlari.",
  },
  "Food & Cooking": {
    category: "Oziq-ovqat va Pazandachilik",
    nameUz: "Oziq-ovqat va Pazandachilik",
    nameEn: "Food & Cooking",
    emoji: "🍳",
    color: "orange",
    gradient: "from-orange-500 to-amber-600",
    bgLight: "bg-orange-50/80",
    borderLight: "border-orange-200",
    textAccent: "text-orange-800",
    description: "Retseptlar, taom tayyorlash usullari, pazandachilik va oshxona anjomlari.",
  },
  "Umumiy Lug‘at Boyligi": {
    category: "Umumiy Lug‘at Boyligi",
    nameUz: "Umumiy Lug‘at Boyligi",
    nameEn: "General Vocabulary",
    emoji: "📚",
    color: "slate",
    gradient: "from-slate-600 to-stone-700",
    bgLight: "bg-slate-50/80",
    borderLight: "border-slate-200",
    textAccent: "text-slate-800",
    description: "Darajaning mustahkam poydevori uchun universal qo‘shimcha leksika.",
  },
  "General Vocabulary": {
    category: "Umumiy Lug‘at Boyligi",
    nameUz: "Umumiy Lug‘at Boyligi",
    nameEn: "General Vocabulary",
    emoji: "📚",
    color: "slate",
    gradient: "from-slate-600 to-stone-700",
    bgLight: "bg-slate-50/80",
    borderLight: "border-slate-200",
    textAccent: "text-slate-800",
    description: "Darajaning mustahkam poydevori uchun universal qo‘shimcha leksika.",
  },
  "Fan va Texnologiya": {
    category: "Fan va Texnologiya",
    nameUz: "Fan va Texnologiya",
    nameEn: "Science & Technology",
    emoji: "🔬",
    color: "cyan",
    gradient: "from-cyan-500 to-blue-600",
    bgLight: "bg-cyan-50/80",
    borderLight: "border-cyan-200",
    textAccent: "text-cyan-800",
    description: "Ilmiy kashfiyotlar, texnologik yutuqlar, kompyuter va elektronika.",
  },
  "Science & Technology": {
    category: "Fan va Texnologiya",
    nameUz: "Fan va Texnologiya",
    nameEn: "Science & Technology",
    emoji: "🔬",
    color: "cyan",
    gradient: "from-cyan-500 to-blue-600",
    bgLight: "bg-cyan-50/80",
    borderLight: "border-cyan-200",
    textAccent: "text-cyan-800",
    description: "Ilmiy kashfiyotlar, texnologik yutuqlar, kompyuter va elektronika.",
  },
  "Kasblar va Faoliyat": {
    category: "Kasblar va Faoliyat",
    nameUz: "Kasblar va Faoliyat",
    nameEn: "Work & Occupations",
    emoji: "👷",
    color: "indigo",
    gradient: "from-indigo-600 to-blue-700",
    bgLight: "bg-indigo-50/80",
    borderLight: "border-indigo-200",
    textAccent: "text-indigo-800",
    description: "Turli soha mutaxassislari, kasblar va ularning mehnat vazifalari.",
  },
  "Work & Occupations": {
    category: "Kasblar va Faoliyat",
    nameUz: "Kasblar va Faoliyat",
    nameEn: "Work & Occupations",
    emoji: "👷",
    color: "indigo",
    gradient: "from-indigo-600 to-blue-700",
    bgLight: "bg-indigo-50/80",
    borderLight: "border-indigo-200",
    textAccent: "text-indigo-800",
    description: "Turli soha mutaxassislari, kasblar va ularning mehnat vazifalari.",
  },
  "Kiyim va Moda": {
    category: "Kiyim va Moda",
    nameUz: "Kiyim va Moda",
    nameEn: "Clothes & Fashion",
    emoji: "👔",
    color: "pink",
    gradient: "from-pink-500 to-rose-600",
    bgLight: "bg-pink-50/80",
    borderLight: "border-pink-200",
    textAccent: "text-pink-800",
    description: "Zamonaviy moda, kiyinish madaniyati, uslublar va matolar.",
  },
  "Clothes & Fashion": {
    category: "Kiyim va Moda",
    nameUz: "Kiyim va Moda",
    nameEn: "Clothes & Fashion",
    emoji: "👔",
    color: "pink",
    gradient: "from-pink-500 to-rose-600",
    bgLight: "bg-pink-50/80",
    borderLight: "border-pink-200",
    textAccent: "text-pink-800",
    description: "Zamonaviy moda, kiyinish madaniyati, uslublar va matolar.",
  },
  "San’at va Madaniyat": {
    category: "San’at va Madaniyat",
    nameUz: "San’at va Madaniyat",
    nameEn: "Arts & Culture",
    emoji: "🎨",
    color: "violet",
    gradient: "from-violet-500 to-purple-600",
    bgLight: "bg-violet-50/80",
    borderLight: "border-violet-200",
    textAccent: "text-violet-800",
    description: "Musiqa, teatr, kino, rasm va tasviriy san’at durdonalari.",
  },
  "Arts & Culture": {
    category: "San’at va Madaniyat",
    nameUz: "San’at va Madaniyat",
    nameEn: "Arts & Culture",
    emoji: "🎨",
    color: "violet",
    gradient: "from-violet-500 to-purple-600",
    bgLight: "bg-violet-50/80",
    borderLight: "border-violet-200",
    textAccent: "text-violet-800",
    description: "Musiqa, teatr, kino, rasm va tasviriy san’at durdonalari.",
  },
  "Jamiyat va Siyosat": {
    category: "Jamiyat va Siyosat",
    nameUz: "Jamiyat va Siyosat",
    nameEn: "Society & Politics",
    emoji: "🏛️",
    color: "slate",
    gradient: "from-slate-600 to-stone-800",
    bgLight: "bg-slate-50/80",
    borderLight: "border-slate-200",
    textAccent: "text-slate-800",
    description: "Davlat boshqaruvi, qonunlar, saylovlar va ijtimoiy jarayonlar.",
  },
  "Society & Politics": {
    category: "Jamiyat va Siyosat",
    nameUz: "Jamiyat va Siyosat",
    nameEn: "Society & Politics",
    emoji: "🏛️",
    color: "slate",
    gradient: "from-slate-600 to-stone-800",
    bgLight: "bg-slate-50/80",
    borderLight: "border-slate-200",
    textAccent: "text-slate-800",
    description: "Davlat boshqaruvi, qonunlar, saylovlar va ijtimoiy jarayonlar.",
  },
  "Kundalik Harakatlar": {
    category: "Kundalik Harakatlar",
    nameUz: "Kundalik Harakatlar",
    nameEn: "Everyday Actions",
    emoji: "🏃",
    color: "blue",
    gradient: "from-blue-500 to-cyan-600",
    bgLight: "bg-blue-50/80",
    borderLight: "border-blue-200",
    textAccent: "text-blue-800",
    description: "Insonning har kungi amallari, harakatlari va xatti-harakatlari.",
  },
  "Everyday Actions": {
    category: "Kundalik Harakatlar",
    nameUz: "Kundalik Harakatlar",
    nameEn: "Everyday Actions",
    emoji: "🏃",
    color: "blue",
    gradient: "from-blue-500 to-cyan-600",
    bgLight: "bg-blue-50/80",
    borderLight: "border-blue-200",
    textAccent: "text-blue-800",
    description: "Insonning har kungi amallari, harakatlari va xatti-harakatlari.",
  },
  "Xarakter va Shaxsiyat": {
    category: "Xarakter va Shaxsiyat",
    nameUz: "Xarakter va Shaxsiyat",
    nameEn: "Personality & Character",
    emoji: "🧠",
    color: "purple",
    gradient: "from-purple-500 to-pink-600",
    bgLight: "bg-purple-50/80",
    borderLight: "border-purple-200",
    textAccent: "text-purple-800",
    description: "Inson fazilatlari, ijobiy va salbiy fe’l-atvor xususiyatlari.",
  },
  "Personality & Character": {
    category: "Xarakter va Shaxsiyat",
    nameUz: "Xarakter va Shaxsiyat",
    nameEn: "Personality & Character",
    emoji: "🧠",
    color: "purple",
    gradient: "from-purple-500 to-pink-600",
    bgLight: "bg-purple-50/80",
    borderLight: "border-purple-200",
    textAccent: "text-purple-800",
    description: "Inson fazilatlari, ijobiy va salbiy fe’l-atvor xususiyatlari.",
  },
  "Pul va Moliya": {
    category: "Pul va Moliya",
    nameUz: "Pul va Moliya",
    nameEn: "Money & Finance",
    emoji: "💰",
    color: "emerald",
    gradient: "from-emerald-500 to-teal-600",
    bgLight: "bg-emerald-50/80",
    borderLight: "border-emerald-200",
    textAccent: "text-emerald-800",
    description: "Bank tizimi, daromad, soliqlar, qarz va sarmoya tushunchalari.",
  },
  "Money & Finance": {
    category: "Pul va Moliya",
    nameUz: "Pul va Moliya",
    nameEn: "Money & Finance",
    emoji: "💰",
    color: "emerald",
    gradient: "from-emerald-500 to-teal-600",
    bgLight: "bg-emerald-50/80",
    borderLight: "border-emerald-200",
    textAccent: "text-emerald-800",
    description: "Bank tizimi, daromad, soliqlar, qarz va sarmoya tushunchalari.",
  },
  "Uy va Ro‘zg‘or Yumushlari": {
    category: "Uy va Ro‘zg‘or Yumushlari",
    nameUz: "Uy va Ro‘zg‘or Yumushlari",
    nameEn: "House & Chores",
    emoji: "🧹",
    color: "amber",
    gradient: "from-amber-500 to-yellow-600",
    bgLight: "bg-amber-50/80",
    borderLight: "border-amber-200",
    textAccent: "text-amber-800",
    description: "Uy tozalash, ta’mirlash, qulayliklar va kundalik ro‘zg‘or ishlari.",
  },
  "House & Chores": {
    category: "Uy va Ro‘zg‘or Yumushlari",
    nameUz: "Uy va Ro‘zg‘or Yumushlari",
    nameEn: "House & Chores",
    emoji: "🧹",
    color: "amber",
    gradient: "from-amber-500 to-yellow-600",
    bgLight: "bg-amber-50/80",
    borderLight: "border-amber-200",
    textAccent: "text-amber-800",
    description: "Uy tozalash, ta’mirlash, qulayliklar va kundalik ro‘zg‘or ishlari.",
  },
  "Tabiat va Geografiya": {
    category: "Tabiat va Geografiya",
    nameUz: "Tabiat va Geografiya",
    nameEn: "Nature & Geography",
    emoji: "🌍",
    color: "green",
    gradient: "from-green-500 to-teal-600",
    bgLight: "bg-green-50/80",
    borderLight: "border-green-200",
    textAccent: "text-green-800",
    description: "Qit’alar, okeanlar, tog‘lar, daryolar va geografik landshaftlar.",
  },
  "Nature & Geography": {
    category: "Tabiat va Geografiya",
    nameUz: "Tabiat va Geografiya",
    nameEn: "Nature & Geography",
    emoji: "🌍",
    color: "green",
    gradient: "from-green-500 to-teal-600",
    bgLight: "bg-green-50/80",
    borderLight: "border-green-200",
    textAccent: "text-green-800",
    description: "Qit’alar, okeanlar, tog‘lar, daryolar va geografik landshaftlar.",
  },
  "Muloqot va Fikrlash": {
    category: "Muloqot va Fikrlash",
    nameUz: "Muloqot va Fikrlash",
    nameEn: "Communication & Thoughts",
    emoji: "💭",
    color: "indigo",
    gradient: "from-indigo-600 to-blue-700",
    bgLight: "bg-indigo-50/80",
    borderLight: "border-indigo-200",
    textAccent: "text-indigo-800",
    description: "O‘z fikrini ifodalash, bahslashish, rozi bo‘lish va mulohaza yuritish.",
  },
  "Communication & Thoughts": {
    category: "Muloqot va Fikrlash",
    nameUz: "Muloqot va Fikrlash",
    nameEn: "Communication & Thoughts",
    emoji: "💭",
    color: "indigo",
    gradient: "from-indigo-600 to-blue-700",
    bgLight: "bg-indigo-50/80",
    borderLight: "border-indigo-200",
    textAccent: "text-indigo-800",
    description: "O‘z fikrini ifodalash, bahslashish, rozi bo‘lish va mulohaza yuritish.",
  },
  "Ko‘ngilochar va OAV": {
    category: "Ko‘ngilochar va OAV",
    nameUz: "Ko‘ngilochar va OAV",
    nameEn: "Entertainment & Media",
    emoji: "🎬",
    color: "rose",
    gradient: "from-rose-500 to-purple-600",
    bgLight: "bg-rose-50/80",
    borderLight: "border-rose-200",
    textAccent: "text-rose-800",
    description: "Kino, televideniye, radio, teatr va tomoshabinlar dunyosi.",
  },
  "Entertainment & Media": {
    category: "Ko‘ngilochar va OAV",
    nameUz: "Ko‘ngilochar va OAV",
    nameEn: "Entertainment & Media",
    emoji: "🎬",
    color: "rose",
    gradient: "from-rose-500 to-purple-600",
    bgLight: "bg-rose-50/80",
    borderLight: "border-rose-200",
    textAccent: "text-rose-800",
    description: "Kino, televideniye, radio, teatr va tomoshabinlar dunyosi.",
  },
  "Munosabatlar va Hissiyotlar": {
    category: "Munosabatlar va Hissiyotlar",
    nameUz: "Munosabatlar va Hissiyotlar",
    nameEn: "Relationships & Emotions",
    emoji: "🤝",
    color: "pink",
    gradient: "from-pink-500 to-rose-600",
    bgLight: "bg-pink-50/80",
    borderLight: "border-pink-200",
    textAccent: "text-pink-800",
    description: "Do‘stlik, sevgi, oilaviy rishtalar va hissiy kechinmalar.",
  },
  "Relationships & Emotions": {
    category: "Munosabatlar va Hissiyotlar",
    nameUz: "Munosabatlar va Hissiyotlar",
    nameEn: "Relationships & Emotions",
    emoji: "🤝",
    color: "pink",
    gradient: "from-pink-500 to-rose-600",
    bgLight: "bg-pink-50/80",
    borderLight: "border-pink-200",
    textAccent: "text-pink-800",
    description: "Do‘stlik, sevgi, oilaviy rishtalar va hissiy kechinmalar.",
  },
  "Jinoyat va Qonun": {
    category: "Jinoyat va Qonun",
    nameUz: "Jinoyat va Qonun",
    nameEn: "Crime & Law",
    emoji: "⚖️",
    color: "slate",
    gradient: "from-slate-600 to-gray-800",
    bgLight: "bg-slate-50/80",
    borderLight: "border-slate-200",
    textAccent: "text-slate-800",
    description: "Sud tizimi, adolat, qonunbuzarlik va huquqiy atamalar.",
  },
  "Crime & Law": {
    category: "Jinoyat va Qonun",
    nameUz: "Jinoyat va Qonun",
    nameEn: "Crime & Law",
    emoji: "⚖️",
    color: "slate",
    gradient: "from-slate-600 to-gray-800",
    bgLight: "bg-slate-50/80",
    borderLight: "border-slate-200",
    textAccent: "text-slate-800",
    description: "Sud tizimi, adolat, qonunbuzarlik va huquqiy atamalar.",
  },
  "Shahar Hayoti va Turar-joy": {
    category: "Shahar Hayoti va Turar-joy",
    nameUz: "Shahar Hayoti va Turar-joy",
    nameEn: "City Life & Housing",
    emoji: "🏙️",
    color: "sky",
    gradient: "from-sky-500 to-indigo-600",
    bgLight: "bg-sky-50/80",
    borderLight: "border-sky-200",
    textAccent: "text-sky-800",
    description: "Zamonaviy shahar infratuzilmasi, binolar va kvartiralar.",
  },
  "City Life & Housing": {
    category: "Shahar Hayoti va Turar-joy",
    nameUz: "Shahar Hayoti va Turar-joy",
    nameEn: "City Life & Housing",
    emoji: "🏙️",
    color: "sky",
    gradient: "from-sky-500 to-indigo-600",
    bgLight: "bg-sky-50/80",
    borderLight: "border-sky-200",
    textAccent: "text-sky-800",
    description: "Zamonaviy shahar infratuzilmasi, binolar va kvartiralar.",
  },
  "Sport va Hordiq": {
    category: "Sport va Hordiq",
    nameUz: "Sport va Hordiq",
    nameEn: "Sports & Leisure",
    emoji: "🏆",
    color: "amber",
    gradient: "from-amber-500 to-orange-600",
    bgLight: "bg-amber-50/80",
    borderLight: "border-amber-200",
    textAccent: "text-amber-800",
    description: "Jismoniy tarbiya, chempionatlar, hakamlar va faol dam olish.",
  },
  "Sports & Leisure": {
    category: "Sport va Hordiq",
    nameUz: "Sport va Hordiq",
    nameEn: "Sports & Leisure",
    emoji: "🏆",
    color: "amber",
    gradient: "from-amber-500 to-orange-600",
    bgLight: "bg-amber-50/80",
    borderLight: "border-amber-200",
    textAccent: "text-amber-800",
    description: "Jismoniy tarbiya, chempionatlar, hakamlar va faol dam olish.",
  },
  "Xarid va Kiyimlar": {
    category: "Xarid va Kiyimlar",
    nameUz: "Xarid va Kiyimlar",
    nameEn: "Shopping & Clothes",
    emoji: "🛍️",
    color: "teal",
    gradient: "from-teal-500 to-emerald-600",
    bgLight: "bg-teal-50/80",
    borderLight: "border-teal-200",
    textAccent: "text-teal-800",
    description: "Kiyim xaridi, kassa, narxlar va savdo markazlari.",
  },
  "Shopping & Clothes": {
    category: "Xarid va Kiyimlar",
    nameUz: "Xarid va Kiyimlar",
    nameEn: "Shopping & Clothes",
    emoji: "🛍️",
    color: "teal",
    gradient: "from-teal-500 to-emerald-600",
    bgLight: "bg-teal-50/80",
    borderLight: "border-teal-200",
    textAccent: "text-teal-800",
    description: "Kiyim xaridi, kassa, narxlar va savdo markazlari.",
  },
  "Ta’lim": {
    category: "Ta’lim",
    nameUz: "Ta’lim",
    nameEn: "Education",
    emoji: "📚",
    color: "indigo",
    gradient: "from-indigo-600 to-purple-700",
    bgLight: "bg-indigo-50/80",
    borderLight: "border-indigo-200",
    textAccent: "text-indigo-800",
    description: "Kollej, universitet, diplomlar va o‘quv jarayoni.",
  },
  "Education": {
    category: "Ta’lim",
    nameUz: "Ta’lim",
    nameEn: "Education",
    emoji: "📚",
    color: "indigo",
    gradient: "from-indigo-600 to-purple-700",
    bgLight: "bg-indigo-50/80",
    borderLight: "border-indigo-200",
    textAccent: "text-indigo-800",
    description: "Kollej, universitet, diplomlar va o‘quv jarayoni.",
  },
  "Ish va Biznes": {
    category: "Ish va Biznes",
    nameUz: "Ish va Biznes",
    nameEn: "Work & Business",
    emoji: "📈",
    color: "blue",
    gradient: "from-blue-600 to-indigo-700",
    bgLight: "bg-blue-50/80",
    borderLight: "border-blue-200",
    textAccent: "text-blue-800",
    description: "Kompaniyalar, xodimlar, mijozlar va boshqaruv.",
  },
  "Work & Business": {
    category: "Ish va Biznes",
    nameUz: "Ish va Biznes",
    nameEn: "Work & Business",
    emoji: "📈",
    color: "blue",
    gradient: "from-blue-600 to-indigo-700",
    bgLight: "bg-blue-50/80",
    borderLight: "border-blue-200",
    textAccent: "text-blue-800",
    description: "Kompaniyalar, xodimlar, mijozlar va boshqaruv.",
  },
  "Salomatlik": {
    category: "Salomatlik",
    nameUz: "Salomatlik",
    nameEn: "Health",
    emoji: "🩺",
    color: "rose",
    gradient: "from-rose-500 to-red-600",
    bgLight: "bg-rose-50/80",
    borderLight: "border-rose-200",
    textAccent: "text-rose-800",
    description: "Tez yordam, dorilar, operatsiya va tibbiy muolajalar.",
  },
  "Health": {
    category: "Salomatlik",
    nameUz: "Salomatlik",
    nameEn: "Health",
    emoji: "🩺",
    color: "rose",
    gradient: "from-rose-500 to-red-600",
    bgLight: "bg-rose-50/80",
    borderLight: "border-rose-200",
    textAccent: "text-rose-800",
    description: "Tez yordam, dorilar, operatsiya va tibbiy muolajalar.",
  },
  "Sayohat": {
    category: "Sayohat",
    nameUz: "Sayohat",
    nameEn: "Travel",
    emoji: "🛫",
    color: "sky",
    gradient: "from-sky-500 to-blue-600",
    bgLight: "bg-sky-50/80",
    borderLight: "border-sky-200",
    textAccent: "text-sky-800",
    description: "Xorijga chiqish, viza, bojxona va manzil sari safar.",
  },
  "Travel": {
    category: "Sayohat",
    nameUz: "Sayohat",
    nameEn: "Travel",
    emoji: "🛫",
    color: "sky",
    gradient: "from-sky-500 to-blue-600",
    bgLight: "bg-sky-50/80",
    borderLight: "border-sky-200",
    textAccent: "text-sky-800",
    description: "Xorijga chiqish, viza, bojxona va manzil sari safar.",
  },
  "Atrof-muhit": {
    category: "Atrof-muhit",
    nameUz: "Atrof-muhit",
    nameEn: "Environment",
    emoji: "♻️",
    color: "emerald",
    gradient: "from-emerald-500 to-teal-600",
    bgLight: "bg-emerald-50/80",
    borderLight: "border-emerald-200",
    textAccent: "text-emerald-800",
    description: "Ifloslanish, chiqindilar, qayta ishlash va tabiiy ofatlar.",
  },
  "Environment": {
    category: "Atrof-muhit",
    nameUz: "Atrof-muhit",
    nameEn: "Environment",
    emoji: "♻️",
    color: "emerald",
    gradient: "from-emerald-500 to-teal-600",
    bgLight: "bg-emerald-50/80",
    borderLight: "border-emerald-200",
    textAccent: "text-emerald-800",
    description: "Ifloslanish, chiqindilar, qayta ishlash va tabiiy ofatlar.",
  },
  "Texnologiya": {
    category: "Texnologiya",
    nameUz: "Texnologiya",
    nameEn: "Technology",
    emoji: "💻",
    color: "cyan",
    gradient: "from-cyan-500 to-blue-600",
    bgLight: "bg-cyan-50/80",
    borderLight: "border-cyan-200",
    textAccent: "text-cyan-800",
    description: "Dasturiy ta’minot, brauzer, ma’lumotlar bazasi va yangilanishlar.",
  },
  "Technology": {
    category: "Texnologiya",
    nameUz: "Texnologiya",
    nameEn: "Technology",
    emoji: "💻",
    color: "cyan",
    gradient: "from-cyan-500 to-blue-600",
    bgLight: "bg-cyan-50/80",
    borderLight: "border-cyan-200",
    textAccent: "text-cyan-800",
    description: "Dasturiy ta’minot, brauzer, ma’lumotlar bazasi va yangilanishlar.",
  },
  "Ta’lim va O‘rganish": {
    category: "Ta’lim va O‘rganish",
    nameUz: "Ta’lim va O‘rganish",
    nameEn: "Education & Learning",
    emoji: "📖",
    color: "violet",
    gradient: "from-violet-600 to-indigo-700",
    bgLight: "bg-violet-50/80",
    borderLight: "border-violet-200",
    textAccent: "text-violet-800",
    description: "Akademik talablar, ilmiy darajalar, metodika va bilim olish.",
  },
  "Education & Learning": {
    category: "Ta’lim va O‘rganish",
    nameUz: "Ta’lim va O‘rganish",
    nameEn: "Education & Learning",
    emoji: "📖",
    color: "violet",
    gradient: "from-violet-600 to-indigo-700",
    bgLight: "bg-violet-50/80",
    borderLight: "border-violet-200",
    textAccent: "text-violet-800",
    description: "Akademik talablar, ilmiy darajalar, metodika va bilim olish.",
  },
  "San’at va Adabiyot": {
    category: "San’at va Adabiyot",
    nameUz: "San’at va Adabiyot",
    nameEn: "Arts & Literature",
    emoji: "🎭",
    color: "purple",
    gradient: "from-purple-500 to-pink-600",
    bgLight: "bg-purple-50/80",
    borderLight: "border-purple-200",
    textAccent: "text-purple-800",
    description: "Adabiy janrlar, romanlar, she’riyat va tasviriy san’at.",
  },
  "Arts & Literature": {
    category: "San’at va Adabiyot",
    nameUz: "San’at va Adabiyot",
    nameEn: "Arts & Literature",
    emoji: "🎭",
    color: "purple",
    gradient: "from-purple-500 to-pink-600",
    bgLight: "bg-purple-50/80",
    borderLight: "border-purple-200",
    textAccent: "text-purple-800",
    description: "Adabiy janrlar, romanlar, she’riyat va tasviriy san’at.",
  },
  "Frazali Fe’llar va Idiomalar": {
    category: "Frazali Fe’llar va Idiomalar",
    nameUz: "Frazali Fe’llar va Idiomalar",
    nameEn: "Phrasal Verbs & Idioms",
    emoji: "💬",
    color: "amber",
    gradient: "from-amber-500 to-orange-600",
    bgLight: "bg-amber-50/80",
    borderLight: "border-amber-200",
    textAccent: "text-amber-800",
    description: "Ko‘chma ma’noli iboralar, maqollar va ravon nutq vositalari.",
  },
  "Phrasal Verbs & Idioms": {
    category: "Frazali Fe’llar va Idiomalar",
    nameUz: "Frazali Fe’llar va Idiomalar",
    nameEn: "Phrasal Verbs & Idioms",
    emoji: "💬",
    color: "amber",
    gradient: "from-amber-500 to-orange-600",
    bgLight: "bg-amber-50/80",
    borderLight: "border-amber-200",
    textAccent: "text-amber-800",
    description: "Ko‘chma ma’noli iboralar, maqollar va ravon nutq vositalari.",
  },
  "Murakkab Sifatlar va Fikrlar": {
    category: "Murakkab Sifatlar va Fikrlar",
    nameUz: "Murakkab Sifatlar va Fikrlar",
    nameEn: "Adjectives & Advanced Opinions",
    emoji: "✨",
    color: "indigo",
    gradient: "from-indigo-500 to-purple-600",
    bgLight: "bg-indigo-50/80",
    borderLight: "border-indigo-200",
    textAccent: "text-indigo-800",
    description: "Chuqur fikrlash, aniq baholash va murakkab sifatlar.",
  },
  "Adjectives & Advanced Opinions": {
    category: "Murakkab Sifatlar va Fikrlar",
    nameUz: "Murakkab Sifatlar va Fikrlar",
    nameEn: "Adjectives & Advanced Opinions",
    emoji: "✨",
    color: "indigo",
    gradient: "from-indigo-500 to-purple-600",
    bgLight: "bg-indigo-50/80",
    borderLight: "border-indigo-200",
    textAccent: "text-indigo-800",
    description: "Chuqur fikrlash, aniq baholash va murakkab sifatlar.",
  },
  "Murakkab Grammatika va Bog‘lovchilar": {
    category: "Murakkab Grammatika va Bog‘lovchilar",
    nameUz: "Murakkab Grammatika va Bog‘lovchilar",
    nameEn: "Grammar & Connectors (Advanced)",
    emoji: "🔗",
    color: "slate",
    gradient: "from-slate-600 to-stone-700",
    bgLight: "bg-slate-50/80",
    borderLight: "border-slate-200",
    textAccent: "text-slate-800",
    description: "Murakkab gap qurilmalari, insho va maqola yozish bog‘lovchilari.",
  },
  "Grammar & Connectors (Advanced)": {
    category: "Murakkab Grammatika va Bog‘lovchilar",
    nameUz: "Murakkab Grammatika va Bog‘lovchilar",
    nameEn: "Grammar & Connectors (Advanced)",
    emoji: "🔗",
    color: "slate",
    gradient: "from-slate-600 to-stone-700",
    bgLight: "bg-slate-50/80",
    borderLight: "border-slate-200",
    textAccent: "text-slate-800",
    description: "Murakkab gap qurilmalari, insho va maqola yozish bog‘lovchilari.",
  },
  "Insoniy Kechinmalar va Tuyg‘ular": {
    category: "Insoniy Kechinmalar va Tuyg‘ular",
    nameUz: "Insoniy Kechinmalar va Tuyg‘ular",
    nameEn: "Emotions & Human Experience",
    emoji: "🧘",
    color: "rose",
    gradient: "from-rose-500 to-pink-600",
    bgLight: "bg-rose-50/80",
    borderLight: "border-rose-200",
    textAccent: "text-rose-800",
    description: "Ichki xotirjamlik, tashvish, umid va insoniy psixologik kechinmalar.",
  },
  "Emotions & Human Experience": {
    category: "Insoniy Kechinmalar va Tuyg‘ular",
    nameUz: "Insoniy Kechinmalar va Tuyg‘ular",
    nameEn: "Emotions & Human Experience",
    emoji: "🧘",
    color: "rose",
    gradient: "from-rose-500 to-pink-600",
    bgLight: "bg-rose-50/80",
    borderLight: "border-rose-200",
    textAccent: "text-rose-800",
    description: "Ichki xotirjamlik, tashvish, umid va insoniy psixologik kechinmalar.",
  },
  "Biznes va Iqtisodiyot": {
    category: "Biznes va Iqtisodiyot",
    nameUz: "Biznes va Iqtisodiyot",
    nameEn: "Business & Economy",
    emoji: "📊",
    color: "blue",
    gradient: "from-blue-600 to-cyan-700",
    bgLight: "bg-blue-50/80",
    borderLight: "border-blue-200",
    textAccent: "text-blue-800",
    description: "Kompaniyalar birlashishi, fond bozori, strategiya va iqtisodiy o‘sish.",
  },
  "Business & Economy": {
    category: "Biznes va Iqtisodiyot",
    nameUz: "Biznes va Iqtisodiyot",
    nameEn: "Business & Economy",
    emoji: "📊",
    color: "blue",
    gradient: "from-blue-600 to-cyan-700",
    bgLight: "bg-blue-50/80",
    borderLight: "border-blue-200",
    textAccent: "text-blue-800",
    description: "Kompaniyalar birlashishi, fond bozori, strategiya va iqtisodiy o‘sish.",
  },
  "Siyosat va Davlat Boshqaruvi": {
    category: "Siyosat va Davlat Boshqaruvi",
    nameUz: "Siyosat va Davlat Boshqaruvi",
    nameEn: "Politics & Government",
    emoji: "🏛️",
    color: "slate",
    gradient: "from-slate-600 to-stone-800",
    bgLight: "bg-slate-50/80",
    borderLight: "border-slate-200",
    textAccent: "text-slate-800",
    description: "Konstitutsiya, diplomatiya, vazirliklar va davlat siyosati.",
  },
  "Politics & Government": {
    category: "Siyosat va Davlat Boshqaruvi",
    nameUz: "Siyosat va Davlat Boshqaruvi",
    nameEn: "Politics & Government",
    emoji: "🏛️",
    color: "slate",
    gradient: "from-slate-600 to-stone-800",
    bgLight: "bg-slate-50/80",
    borderLight: "border-slate-200",
    textAccent: "text-slate-800",
    description: "Konstitutsiya, diplomatiya, vazirliklar va davlat siyosati.",
  },
  "Atrof-muhit va Ilm-fan": {
    category: "Atrof-muhit va Ilm-fan",
    nameUz: "Atrof-muhit va Ilm-fan",
    nameEn: "Environment & Science",
    emoji: "🔬",
    color: "emerald",
    gradient: "from-emerald-500 to-teal-600",
    bgLight: "bg-emerald-50/80",
    borderLight: "border-emerald-200",
    textAccent: "text-emerald-800",
    description: "Ilmiy tajribalar, laboratoriya, biologiya, kimyo va ekotizim.",
  },
  "Environment & Science": {
    category: "Atrof-muhit va Ilm-fan",
    nameUz: "Atrof-muhit va Ilm-fan",
    nameEn: "Environment & Science",
    emoji: "🔬",
    color: "emerald",
    gradient: "from-emerald-500 to-teal-600",
    bgLight: "bg-emerald-50/80",
    borderLight: "border-emerald-200",
    textAccent: "text-emerald-800",
    description: "Ilmiy tajribalar, laboratoriya, biologiya, kimyo va ekotizim.",
  },
  "Salomatlik va Tibbiyot": {
    category: "Salomatlik va Tibbiyot",
    nameUz: "Salomatlik va Tibbiyot",
    nameEn: "Health & Medicine",
    emoji: "🏥",
    color: "rose",
    gradient: "from-rose-500 to-red-600",
    bgLight: "bg-rose-50/80",
    borderLight: "border-rose-200",
    textAccent: "text-rose-800",
    description: "Klinik tashxislar, dori-darmonlar, emlash va jamoat salomatligi.",
  },
  "Health & Medicine": {
    category: "Salomatlik va Tibbiyot",
    nameUz: "Salomatlik va Tibbiyot",
    nameEn: "Health & Medicine",
    emoji: "🏥",
    color: "rose",
    gradient: "from-rose-500 to-red-600",
    bgLight: "bg-rose-50/80",
    borderLight: "border-rose-200",
    textAccent: "text-rose-800",
    description: "Klinik tashxislar, dori-darmonlar, emlash va jamoat salomatligi.",
  },
  "Media va Kommunikatsiya": {
    category: "Media va Kommunikatsiya",
    nameUz: "Media va Kommunikatsiya",
    nameEn: "Media & Communication",
    emoji: "📡",
    color: "cyan",
    gradient: "from-cyan-500 to-blue-600",
    bgLight: "bg-cyan-50/80",
    borderLight: "border-cyan-200",
    textAccent: "text-cyan-800",
    description: "OAV erkinligi, jurnalistika, yangiliklar va jamoatchilik fikri.",
  },
  "Media & Communication": {
    category: "Media va Kommunikatsiya",
    nameUz: "Media va Kommunikatsiya",
    nameEn: "Media & Communication",
    emoji: "📡",
    color: "cyan",
    gradient: "from-cyan-500 to-blue-600",
    bgLight: "bg-cyan-50/80",
    borderLight: "border-cyan-200",
    textAccent: "text-cyan-800",
    description: "OAV erkinligi, jurnalistika, yangiliklar va jamoatchilik fikri.",
  },
  "Psixologiya va Xulq-atvor": {
    category: "Psixologiya va Xulq-atvor",
    nameUz: "Psixologiya va Xulq-atvor",
    nameEn: "Psychology & Behavior",
    emoji: "🧠",
    color: "purple",
    gradient: "from-purple-500 to-indigo-600",
    bgLight: "bg-purple-50/80",
    borderLight: "border-purple-200",
    textAccent: "text-purple-800",
    description: "Inson ruhiyati, idrok, xulq-atvor omillari va motivatsiya.",
  },
  "Psychology & Behavior": {
    category: "Psixologiya va Xulq-atvor",
    nameUz: "Psixologiya va Xulq-atvor",
    nameEn: "Psychology & Behavior",
    emoji: "🧠",
    color: "purple",
    gradient: "from-purple-500 to-indigo-600",
    bgLight: "bg-purple-50/80",
    borderLight: "border-purple-200",
    textAccent: "text-purple-800",
    description: "Inson ruhiyati, idrok, xulq-atvor omillari va motivatsiya.",
  },
  "Qonun va Adolat": {
    category: "Qonun va Adolat",
    nameUz: "Qonun va Adolat",
    nameEn: "Law & Justice",
    emoji: "⚖️",
    color: "slate",
    gradient: "from-slate-600 to-stone-800",
    bgLight: "bg-slate-50/80",
    borderLight: "border-slate-200",
    textAccent: "text-slate-800",
    description: "Sud jarayoni, advokatlik, huquqiy javobgarlik va hukmlar.",
  },
  "Law & Justice": {
    category: "Qonun va Adolat",
    nameUz: "Qonun va Adolat",
    nameEn: "Law & Justice",
    emoji: "⚖️",
    color: "slate",
    gradient: "from-slate-600 to-stone-800",
    bgLight: "bg-slate-50/80",
    borderLight: "border-slate-200",
    textAccent: "text-slate-800",
    description: "Sud jarayoni, advokatlik, huquqiy javobgarlik va hukmlar.",
  },
  "Global Muammolar": {
    category: "Global Muammolar",
    nameUz: "Global Muammolar",
    nameEn: "Global Issues",
    emoji: "🌐",
    color: "blue",
    gradient: "from-blue-600 to-teal-700",
    bgLight: "bg-blue-50/80",
    borderLight: "border-blue-200",
    textAccent: "text-blue-800",
    description: "Xalqaro inqirozlar, qashshoqlik, migratsiya va tinchlik masalalari.",
  },
  "Global Issues": {
    category: "Global Muammolar",
    nameUz: "Global Muammolar",
    nameEn: "Global Issues",
    emoji: "🌐",
    color: "blue",
    gradient: "from-blue-600 to-teal-700",
    bgLight: "bg-blue-50/80",
    borderLight: "border-blue-200",
    textAccent: "text-blue-800",
    description: "Xalqaro inqirozlar, qashshoqlik, migratsiya va tinchlik masalalari.",
  },
  "Atrof-muhit va Tabiat": {
    category: "Atrof-muhit va Tabiat",
    nameUz: "Atrof-muhit va Tabiat",
    nameEn: "Environment & Nature",
    emoji: "🌱",
    color: "emerald",
    gradient: "from-emerald-500 to-green-600",
    bgLight: "bg-emerald-50/80",
    borderLight: "border-emerald-200",
    textAccent: "text-emerald-800",
    description: "Bioxilma-xillik, atmosfera, iqlim o‘zgarishi va tabiatni muhofaza qilish.",
  },
  "Environment & Nature": {
    category: "Atrof-muhit va Tabiat",
    nameUz: "Atrof-muhit va Tabiat",
    nameEn: "Environment & Nature",
    emoji: "🌱",
    color: "emerald",
    gradient: "from-emerald-500 to-green-600",
    bgLight: "bg-emerald-50/80",
    borderLight: "border-emerald-200",
    textAccent: "text-emerald-800",
    description: "Bioxilma-xillik, atmosfera, iqlim o‘zgarishi va tabiatni muhofaza qilish.",
  },
  "Biznes va Mehnat": {
    category: "Biznes va Mehnat",
    nameUz: "Biznes va Mehnat",
    nameEn: "Business & Work",
    emoji: "💼",
    color: "indigo",
    gradient: "from-indigo-600 to-blue-700",
    bgLight: "bg-indigo-50/80",
    borderLight: "border-indigo-200",
    textAccent: "text-indigo-800",
    description: "Korxona boshqaruvi, investitsiyalar, iqtisodiy tahlil va korporatsiya.",
  },
  "Business & Work": {
    category: "Biznes va Mehnat",
    nameUz: "Biznes va Mehnat",
    nameEn: "Business & Work",
    emoji: "💼",
    color: "indigo",
    gradient: "from-indigo-600 to-blue-700",
    bgLight: "bg-indigo-50/80",
    borderLight: "border-indigo-200",
    textAccent: "text-indigo-800",
    description: "Korxona boshqaruvi, investitsiyalar, iqtisodiy tahlil va korporatsiya.",
  },
  "Abstrakt Tushunchalar va Otlar": {
    category: "Abstrakt Tushunchalar va Otlar",
    nameUz: "Abstrakt Tushunchalar va Otlar",
    nameEn: "Abstract Concepts & General Nouns",
    emoji: "💭",
    color: "purple",
    gradient: "from-purple-500 to-indigo-600",
    bgLight: "bg-purple-50/80",
    borderLight: "border-purple-200",
    textAccent: "text-purple-800",
    description: "Murakkab g‘oyalar, falsafiy tushunchalar va mavhum ma’noli otlar.",
  },
  "Abstract Concepts & General Nouns": {
    category: "Abstrakt Tushunchalar va Otlar",
    nameUz: "Abstrakt Tushunchalar va Otlar",
    nameEn: "Abstract Concepts & General Nouns",
    emoji: "💭",
    color: "purple",
    gradient: "from-purple-500 to-indigo-600",
    bgLight: "bg-purple-50/80",
    borderLight: "border-purple-200",
    textAccent: "text-purple-800",
    description: "Murakkab g‘oyalar, falsafiy tushunchalar va mavhum ma’noli otlar.",
  },
  "Aqliy va Harakat Fe’llari": {
    category: "Aqliy va Harakat Fe’llari",
    nameUz: "Aqliy va Harakat Fe’llari",
    nameEn: "Action & Mental Verbs",
    emoji: "⚡",
    color: "amber",
    gradient: "from-amber-500 to-orange-600",
    bgLight: "bg-amber-50/80",
    borderLight: "border-amber-200",
    textAccent: "text-amber-800",
    description: "Tafakkur qilish, baholash, xulosa chiqarish va intellektual harakat fe’llari.",
  },
  "Action & Mental Verbs": {
    category: "Aqliy va Harakat Fe’llari",
    nameUz: "Aqliy va Harakat Fe’llari",
    nameEn: "Action & Mental Verbs",
    emoji: "⚡",
    color: "amber",
    gradient: "from-amber-500 to-orange-600",
    bgLight: "bg-amber-50/80",
    borderLight: "border-amber-200",
    textAccent: "text-amber-800",
    description: "Tafakkur qilish, baholash, xulosa chiqarish va intellektual harakat fe’llari.",
  },
  "Biznes va Tijorat": {
    category: "Biznes va Tijorat",
    nameUz: "Biznes va Tijorat",
    nameEn: "Business",
    emoji: "💼",
    color: "indigo",
    gradient: "from-indigo-600 to-blue-700",
    bgLight: "bg-indigo-50/80",
    borderLight: "border-indigo-200",
    textAccent: "text-indigo-800",
    description: "Tijorat, bozor va korporativ faoliyat.",
  },
  "Business": {
    category: "Biznes va Tijorat",
    nameUz: "Biznes va Tijorat",
    nameEn: "Business",
    emoji: "💼",
    color: "indigo",
    gradient: "from-indigo-600 to-blue-700",
    bgLight: "bg-indigo-50/80",
    borderLight: "border-indigo-200",
    textAccent: "text-indigo-800",
    description: "Tijorat, bozor va korporativ faoliyat.",
  },
  "Jamiyat va Ijtimoiy Hayot": {
    category: "Jamiyat va Ijtimoiy Hayot",
    nameUz: "Jamiyat va Ijtimoiy Hayot",
    nameEn: "Society",
    emoji: "👥",
    color: "blue",
    gradient: "from-blue-600 to-indigo-700",
    bgLight: "bg-blue-50/80",
    borderLight: "border-blue-200",
    textAccent: "text-blue-800",
    description: "Ijtimoiy tizim, jamoatchilik va fuqarolik munosabatlari.",
  },
  "Society": {
    category: "Jamiyat va Ijtimoiy Hayot",
    nameUz: "Jamiyat va Ijtimoiy Hayot",
    nameEn: "Society",
    emoji: "👥",
    color: "blue",
    gradient: "from-blue-600 to-indigo-700",
    bgLight: "bg-blue-50/80",
    borderLight: "border-blue-200",
    textAccent: "text-blue-800",
    description: "Ijtimoiy tizim, jamoatchilik va fuqarolik munosabatlari.",
  },
  "Mehnat va Kasb": {
    category: "Mehnat va Kasb",
    nameUz: "Mehnat va Kasb",
    nameEn: "Work",
    emoji: "💼",
    color: "indigo",
    gradient: "from-indigo-600 to-blue-700",
    bgLight: "bg-indigo-50/80",
    borderLight: "border-indigo-200",
    textAccent: "text-indigo-800",
    description: "Kasbiy vazifalar va mehnat jarayoni.",
  },
  "Work": {
    category: "Mehnat va Kasb",
    nameUz: "Mehnat va Kasb",
    nameEn: "Work",
    emoji: "💼",
    color: "indigo",
    gradient: "from-indigo-600 to-blue-700",
    bgLight: "bg-indigo-50/80",
    borderLight: "border-indigo-200",
    textAccent: "text-indigo-800",
    description: "Kasbiy vazifalar va mehnat jarayoni.",
  },
  "Ilm-fan": {
    category: "Ilm-fan",
    nameUz: "Ilm-fan",
    nameEn: "Science",
    emoji: "🔬",
    color: "cyan",
    gradient: "from-cyan-500 to-blue-600",
    bgLight: "bg-cyan-50/80",
    borderLight: "border-cyan-200",
    textAccent: "text-cyan-800",
    description: "Ilmiy tushunchalar va tabiiy qonuniyatlar.",
  },
  "Science": {
    category: "Ilm-fan",
    nameUz: "Ilm-fan",
    nameEn: "Science",
    emoji: "🔬",
    color: "cyan",
    gradient: "from-cyan-500 to-blue-600",
    bgLight: "bg-cyan-50/80",
    borderLight: "border-cyan-200",
    textAccent: "text-cyan-800",
    description: "Ilmiy tushunchalar va tabiiy qonuniyatlar.",
  },
  "Psixologiya": {
    category: "Psixologiya",
    nameUz: "Psixologiya",
    nameEn: "Psychology",
    emoji: "🧠",
    color: "purple",
    gradient: "from-purple-500 to-indigo-600",
    bgLight: "bg-purple-50/80",
    borderLight: "border-purple-200",
    textAccent: "text-purple-800",
    description: "Ruhiyat, fe’l-atvor va idrok qilish.",
  },
  "Psychology": {
    category: "Psixologiya",
    nameUz: "Psixologiya",
    nameEn: "Psychology",
    emoji: "🧠",
    color: "purple",
    gradient: "from-purple-500 to-indigo-600",
    bgLight: "bg-purple-50/80",
    borderLight: "border-purple-200",
    textAccent: "text-purple-800",
    description: "Ruhiyat, fe’l-atvor va idrok qilish.",
  },
  "Muloqot va Axborot": {
    category: "Muloqot va Axborot",
    nameUz: "Muloqot va Axborot",
    nameEn: "Communication",
    emoji: "🗣️",
    color: "blue",
    gradient: "from-blue-600 to-indigo-700",
    bgLight: "bg-blue-50/80",
    borderLight: "border-blue-200",
    textAccent: "text-blue-800",
    description: "Muloqot qilish, fikr yetkazish va suhbat.",
  },
  "Communication": {
    category: "Muloqot va Axborot",
    nameUz: "Muloqot va Axborot",
    nameEn: "Communication",
    emoji: "🗣️",
    color: "blue",
    gradient: "from-blue-600 to-indigo-700",
    bgLight: "bg-blue-50/80",
    borderLight: "border-blue-200",
    textAccent: "text-blue-800",
    description: "Muloqot qilish, fikr yetkazish va suhbat.",
  },
  "Qonun va Huquq": {
    category: "Qonun va Huquq",
    nameUz: "Qonun va Huquq",
    nameEn: "Law",
    emoji: "⚖️",
    color: "slate",
    gradient: "from-slate-600 to-stone-800",
    bgLight: "bg-slate-50/80",
    borderLight: "border-slate-200",
    textAccent: "text-slate-800",
    description: "Huquqiy normalar, sud va qonunchilik.",
  },
  "Law": {
    category: "Qonun va Huquq",
    nameUz: "Qonun va Huquq",
    nameEn: "Law",
    emoji: "⚖️",
    color: "slate",
    gradient: "from-slate-600 to-stone-800",
    bgLight: "bg-slate-50/80",
    borderLight: "border-slate-200",
    textAccent: "text-slate-800",
    description: "Huquqiy normalar, sud va qonunchilik.",
  },
  "Kundalik Turmush": {
    category: "Kundalik Turmush",
    nameUz: "Kundalik Turmush",
    nameEn: "Everyday Life",
    emoji: "☕",
    color: "amber",
    gradient: "from-amber-500 to-orange-600",
    bgLight: "bg-amber-50/80",
    borderLight: "border-amber-200",
    textAccent: "text-amber-800",
    description: "Har kungi kundalik vaziyatlar va oddiy hayot.",
  },
  "Everyday Life": {
    category: "Kundalik Turmush",
    nameUz: "Kundalik Turmush",
    nameEn: "Everyday Life",
    emoji: "☕",
    color: "amber",
    gradient: "from-amber-500 to-orange-600",
    bgLight: "bg-amber-50/80",
    borderLight: "border-amber-200",
    textAccent: "text-amber-800",
    description: "Har kungi kundalik vaziyatlar va oddiy hayot.",
  },
  "Siyosat": {
    category: "Siyosat",
    nameUz: "Siyosat",
    nameEn: "Politics",
    emoji: "🏛️",
    color: "slate",
    gradient: "from-slate-600 to-stone-800",
    bgLight: "bg-slate-50/80",
    borderLight: "border-slate-200",
    textAccent: "text-slate-800",
    description: "Siyosiy munosabatlar va davlat tuzilishi.",
  },
  "Politics": {
    category: "Siyosat",
    nameUz: "Siyosat",
    nameEn: "Politics",
    emoji: "🏛️",
    color: "slate",
    gradient: "from-slate-600 to-stone-800",
    bgLight: "bg-slate-50/80",
    borderLight: "border-slate-200",
    textAccent: "text-slate-800",
    description: "Siyosiy munosabatlar va davlat tuzilishi.",
  },
  "Iqtisodiyot": {
    category: "Iqtisodiyot",
    nameUz: "Iqtisodiyot",
    nameEn: "Economy",
    emoji: "📊",
    color: "emerald",
    gradient: "from-emerald-500 to-teal-600",
    bgLight: "bg-emerald-50/80",
    borderLight: "border-emerald-200",
    textAccent: "text-emerald-800",
    description: "Iqtisodiy jarayonlar, bozor va moliyaviy muvozanat.",
  },
  "Economy": {
    category: "Iqtisodiyot",
    nameUz: "Iqtisodiyot",
    nameEn: "Economy",
    emoji: "📊",
    color: "emerald",
    gradient: "from-emerald-500 to-teal-600",
    bgLight: "bg-emerald-50/80",
    borderLight: "border-emerald-200",
    textAccent: "text-emerald-800",
    description: "Iqtisodiy jarayonlar, bozor va moliyaviy muvozanat.",
  },
  "Til va Lingvistika": {
    category: "Til va Lingvistika",
    nameUz: "Til va Lingvistika",
    nameEn: "Language & Linguistics",
    emoji: "🗣️",
    color: "indigo",
    gradient: "from-indigo-600 to-purple-700",
    bgLight: "bg-indigo-50/80",
    borderLight: "border-indigo-200",
    textAccent: "text-indigo-800",
    description: "Nutq, til vositalari, uslub va so‘z boyligi.",
  },
  "Language & Linguistics": {
    category: "Til va Lingvistika",
    nameUz: "Til va Lingvistika",
    nameEn: "Language & Linguistics",
    emoji: "🗣️",
    color: "indigo",
    gradient: "from-indigo-600 to-purple-700",
    bgLight: "bg-indigo-50/80",
    borderLight: "border-indigo-200",
    textAccent: "text-indigo-800",
    description: "Nutq, til vositalari, uslub va so‘z boyligi.",
  },
  "Xulq-atvor": {
    category: "Xulq-atvor",
    nameUz: "Xulq-atvor",
    nameEn: "Behavior",
    emoji: "🚶",
    color: "purple",
    gradient: "from-purple-500 to-pink-600",
    bgLight: "bg-purple-50/80",
    borderLight: "border-purple-200",
    textAccent: "text-purple-800",
    description: "Xulq, xatti-harakat va insoniy reaksiyalar.",
  },
  "Behavior": {
    category: "Xulq-atvor",
    nameUz: "Xulq-atvor",
    nameEn: "Behavior",
    emoji: "🚶",
    color: "purple",
    gradient: "from-purple-500 to-pink-600",
    bgLight: "bg-purple-50/80",
    borderLight: "border-purple-200",
    textAccent: "text-purple-800",
    description: "Xulq, xatti-harakat va insoniy reaksiyalar.",
  },
  "Adabiyot": {
    category: "Adabiyot",
    nameUz: "Adabiyot",
    nameEn: "Literature",
    emoji: "📚",
    color: "rose",
    gradient: "from-rose-500 to-purple-600",
    bgLight: "bg-rose-50/80",
    borderLight: "border-rose-200",
    textAccent: "text-rose-800",
    description: "Badiiy ijod, hikoyalar va adabiy meros.",
  },
  "Literature": {
    category: "Adabiyot",
    nameUz: "Adabiyot",
    nameEn: "Literature",
    emoji: "📚",
    color: "rose",
    gradient: "from-rose-500 to-purple-600",
    bgLight: "bg-rose-50/80",
    borderLight: "border-rose-200",
    textAccent: "text-rose-800",
    description: "Badiiy ijod, hikoyalar va adabiy meros.",
  },
  "Falsafa": {
    category: "Falsafa",
    nameUz: "Falsafa",
    nameEn: "Philosophy",
    emoji: "💭",
    color: "amber",
    gradient: "from-amber-600 to-yellow-700",
    bgLight: "bg-amber-50/80",
    borderLight: "border-amber-200",
    textAccent: "text-amber-900",
    description: "Borliq, haqiqat va inson hayoti ma’nosi.",
  },
  "Philosophy": {
    category: "Falsafa",
    nameUz: "Falsafa",
    nameEn: "Philosophy",
    emoji: "💭",
    color: "amber",
    gradient: "from-amber-600 to-yellow-700",
    bgLight: "bg-amber-50/80",
    borderLight: "border-amber-200",
    textAccent: "text-amber-900",
    description: "Borliq, haqiqat va inson hayoti ma’nosi.",
  },
  "Akademik Tadqiqotlar": {
    category: "Akademik Tadqiqotlar",
    nameUz: "Akademik Tadqiqotlar",
    nameEn: "Academic & Research",
    emoji: "🔬",
    color: "violet",
    gradient: "from-violet-600 to-purple-700",
    bgLight: "bg-violet-50/80",
    borderLight: "border-violet-200",
    textAccent: "text-violet-800",
    description: "Ilmiy dissertatsiyalar, gipotezalar, ilmiy maqolalar va metodologiya.",
  },
  "Academic & Research": {
    category: "Akademik Tadqiqotlar",
    nameUz: "Akademik Tadqiqotlar",
    nameEn: "Academic & Research",
    emoji: "🔬",
    color: "violet",
    gradient: "from-violet-600 to-purple-700",
    bgLight: "bg-violet-50/80",
    borderLight: "border-violet-200",
    textAccent: "text-violet-800",
    description: "Ilmiy dissertatsiyalar, gipotezalar, ilmiy maqolalar va metodologiya.",
  },
  "Adabiyot va Notiqlik": {
    category: "Adabiyot va Notiqlik",
    nameUz: "Adabiyot va Notiqlik",
    nameEn: "Literature & Rhetoric",
    emoji: "📜",
    color: "amber",
    gradient: "from-amber-600 to-yellow-700",
    bgLight: "bg-amber-50/80",
    borderLight: "border-amber-200",
    textAccent: "text-amber-900",
    description: "Badiiy vositalar, nutq san’ati, ritorika va adabiy uslublar.",
  },
  "Literature & Rhetoric": {
    category: "Adabiyot va Notiqlik",
    nameUz: "Adabiyot va Notiqlik",
    nameEn: "Literature & Rhetoric",
    emoji: "📜",
    color: "amber",
    gradient: "from-amber-600 to-yellow-700",
    bgLight: "bg-amber-50/80",
    borderLight: "border-amber-200",
    textAccent: "text-amber-900",
    description: "Badiiy vositalar, nutq san’ati, ritorika va adabiy uslublar.",
  },
  "Idiomalar va Murakkab Iboralar": {
    category: "Idiomalar va Murakkab Iboralar",
    nameUz: "Idiomalar va Murakkab Iboralar",
    nameEn: "Idioms & Advanced Expressions",
    emoji: "🗣️",
    color: "rose",
    gradient: "from-rose-500 to-pink-600",
    bgLight: "bg-rose-50/80",
    borderLight: "border-rose-200",
    textAccent: "text-rose-800",
    description: "Ona tili darajasidagi boy iboralar, metaforalar va turg‘un birikmalar.",
  },
  "Idioms & Advanced Expressions": {
    category: "Idiomalar va Murakkab Iboralar",
    nameUz: "Idiomalar va Murakkab Iboralar",
    nameEn: "Idioms & Advanced Expressions",
    emoji: "🗣️",
    color: "rose",
    gradient: "from-rose-500 to-pink-600",
    bgLight: "bg-rose-50/80",
    borderLight: "border-rose-200",
    textAccent: "text-rose-800",
    description: "Ona tili darajasidagi boy iboralar, metaforalar va turg‘un birikmalar.",
  },
  "Nozik Ma’noli Sifatlar": {
    category: "Nozik Ma’noli Sifatlar",
    nameUz: "Nozik Ma’noli Sifatlar",
    nameEn: "Advanced Adjectives & Nuance",
    emoji: "💎",
    color: "teal",
    gradient: "from-teal-500 to-cyan-600",
    bgLight: "bg-teal-50/80",
    borderLight: "border-teal-200",
    textAccent: "text-teal-800",
    description: "Nozik ma’nodosh sifatlar, kamyob va yuqori saviyadagi sifatlar.",
  },
  "Advanced Adjectives & Nuance": {
    category: "Nozik Ma’noli Sifatlar",
    nameUz: "Nozik Ma’noli Sifatlar",
    nameEn: "Advanced Adjectives & Nuance",
    emoji: "💎",
    color: "teal",
    gradient: "from-teal-500 to-cyan-600",
    bgLight: "bg-teal-50/80",
    borderLight: "border-teal-200",
    textAccent: "text-teal-800",
    description: "Nozik ma’nodosh sifatlar, kamyob va yuqori saviyadagi sifatlar.",
  },
  "Diskurs Vositalari va Grammatika": {
    category: "Diskurs Vositalari va Grammatika",
    nameUz: "Diskurs Vositalari va Grammatika",
    nameEn: "Advanced Grammar & Discourse Markers",
    emoji: "🧩",
    color: "slate",
    gradient: "from-slate-600 to-stone-700",
    bgLight: "bg-slate-50/80",
    borderLight: "border-slate-200",
    textAccent: "text-slate-800",
    description: "Murakkab insho va akademik taqdimotlar uchun leksik ko‘priklar.",
  },
  "Advanced Grammar & Discourse Markers": {
    category: "Diskurs Vositalari va Grammatika",
    nameUz: "Diskurs Vositalari va Grammatika",
    nameEn: "Advanced Grammar & Discourse Markers",
    emoji: "🧩",
    color: "slate",
    gradient: "from-slate-600 to-stone-700",
    bgLight: "bg-slate-50/80",
    borderLight: "border-slate-200",
    textAccent: "text-slate-800",
    description: "Murakkab insho va akademik taqdimotlar uchun leksik ko‘priklar.",
  },
  "Inson Tabiati va Axloq": {
    category: "Inson Tabiati va Axloq",
    nameUz: "Inson Tabiati va Axloq",
    nameEn: "Human Nature & Ethics",
    emoji: "⚖️",
    color: "indigo",
    gradient: "from-indigo-600 to-blue-700",
    bgLight: "bg-indigo-50/80",
    borderLight: "border-indigo-200",
    textAccent: "text-indigo-800",
    description: "Axloqiy qadriyatlar, vijdon, burch va insoniy fazilatlar.",
  },
  "Human Nature & Ethics": {
    category: "Inson Tabiati va Axloq",
    nameUz: "Inson Tabiati va Axloq",
    nameEn: "Human Nature & Ethics",
    emoji: "⚖️",
    color: "indigo",
    gradient: "from-indigo-600 to-blue-700",
    bgLight: "bg-indigo-50/80",
    borderLight: "border-indigo-200",
    textAccent: "text-indigo-800",
    description: "Axloqiy qadriyatlar, vijdon, burch va insoniy fazilatlar.",
  },
  "Iqtisodiyot va Moliya": {
    category: "Iqtisodiyot va Moliya",
    nameUz: "Iqtisodiyot va Moliya",
    nameEn: "Economics & Finance",
    emoji: "📈",
    color: "emerald",
    gradient: "from-emerald-500 to-teal-600",
    bgLight: "bg-emerald-50/80",
    borderLight: "border-emerald-200",
    textAccent: "text-emerald-800",
    description: "Makroiqtisodiyot, pul-kredit siyosati, bozor kon’yunkturasi va likvidlik.",
  },
  "Economics & Finance": {
    category: "Iqtisodiyot va Moliya",
    nameUz: "Iqtisodiyot va Moliya",
    nameEn: "Economics & Finance",
    emoji: "📈",
    color: "emerald",
    gradient: "from-emerald-500 to-teal-600",
    bgLight: "bg-emerald-50/80",
    borderLight: "border-emerald-200",
    textAccent: "text-emerald-800",
    description: "Makroiqtisodiyot, pul-kredit siyosati, bozor kon’yunkturasi va likvidlik.",
  },
  "Davlat Boshqaruvi va Huquq": {
    category: "Davlat Boshqaruvi va Huquq",
    nameUz: "Davlat Boshqaruvi va Huquq",
    nameEn: "Governance & Law",
    emoji: "🏛️",
    color: "slate",
    gradient: "from-slate-600 to-stone-800",
    bgLight: "bg-slate-50/80",
    borderLight: "border-slate-200",
    textAccent: "text-slate-800",
    description: "Qonun ustuvorligi, konstitutsiyaviy huquq, yurisprudensiya va suverenitet.",
  },
  "Governance & Law": {
    category: "Davlat Boshqaruvi va Huquq",
    nameUz: "Davlat Boshqaruvi va Huquq",
    nameEn: "Governance & Law",
    emoji: "🏛️",
    color: "slate",
    gradient: "from-slate-600 to-stone-800",
    bgLight: "bg-slate-50/80",
    borderLight: "border-slate-200",
    textAccent: "text-slate-800",
    description: "Qonun ustuvorligi, konstitutsiyaviy huquq, yurisprudensiya va suverenitet.",
  },
  "Tibbiyot va Jamoat Salomatligi": {
    category: "Tibbiyot va Jamoat Salomatligi",
    nameUz: "Tibbiyot va Jamoat Salomatligi",
    nameEn: "Medicine & Public Health",
    emoji: "🏥",
    color: "rose",
    gradient: "from-rose-500 to-red-600",
    bgLight: "bg-rose-50/80",
    borderLight: "border-rose-200",
    textAccent: "text-rose-800",
    description: "Klinik tushunchalar, bioetika, epidemiologiya va kasalliklarning oldini olish.",
  },
  "Medicine & Public Health": {
    category: "Tibbiyot va Jamoat Salomatligi",
    nameUz: "Tibbiyot va Jamoat Salomatligi",
    nameEn: "Medicine & Public Health",
    emoji: "🏥",
    color: "rose",
    gradient: "from-rose-500 to-red-600",
    bgLight: "bg-rose-50/80",
    borderLight: "border-rose-200",
    textAccent: "text-rose-800",
    description: "Klinik tushunchalar, bioetika, epidemiologiya va kasalliklarning oldini olish.",
  },
  "OAV va Jurnalistika": {
    category: "OAV va Jurnalistika",
    nameUz: "OAV va Jurnalistika",
    nameEn: "Media",
    emoji: "📡",
    color: "cyan",
    gradient: "from-cyan-500 to-blue-600",
    bgLight: "bg-cyan-50/80",
    borderLight: "border-cyan-200",
    textAccent: "text-cyan-800",
    description: "Matbuot, televideniye va axborot vositalari.",
  },
  "Media": {
    category: "OAV va Jurnalistika",
    nameUz: "OAV va Jurnalistika",
    nameEn: "Media",
    emoji: "📡",
    color: "cyan",
    gradient: "from-cyan-500 to-blue-600",
    bgLight: "bg-cyan-50/80",
    borderLight: "border-cyan-200",
    textAccent: "text-cyan-800",
    description: "Matbuot, televideniye va axborot vositalari.",
  },
  "Kognitiv Psixologiya va Idrok": {
    category: "Kognitiv Psixologiya va Idrok",
    nameUz: "Kognitiv Psixologiya va Idrok",
    nameEn: "Psychology & Cognition",
    emoji: "🧠",
    color: "purple",
    gradient: "from-purple-500 to-indigo-600",
    bgLight: "bg-purple-50/80",
    borderLight: "border-purple-200",
    textAccent: "text-purple-800",
    description: "Xotira, fikrlash xatoliklari, hissiy aql va insoniy qaror qabul qilish mexanizmi.",
  },
  "Psychology & Cognition": {
    category: "Kognitiv Psixologiya va Idrok",
    nameUz: "Kognitiv Psixologiya va Idrok",
    nameEn: "Psychology & Cognition",
    emoji: "🧠",
    color: "purple",
    gradient: "from-purple-500 to-indigo-600",
    bgLight: "bg-purple-50/80",
    borderLight: "border-purple-200",
    textAccent: "text-purple-800",
    description: "Xotira, fikrlash xatoliklari, hissiy aql va insoniy qaror qabul qilish mexanizmi.",
  },
  "Atrof-muhit va Barqarorlik": {
    category: "Atrof-muhit va Barqarorlik",
    nameUz: "Atrof-muhit va Barqarorlik",
    nameEn: "Environment & Sustainability",
    emoji: "🌿",
    color: "emerald",
    gradient: "from-emerald-500 to-green-600",
    bgLight: "bg-emerald-50/80",
    borderLight: "border-emerald-200",
    textAccent: "text-emerald-800",
    description: "Barqaror rivojlanish, uglerod neytralligi va global ekologik maqsadlar.",
  },
  "Environment & Sustainability": {
    category: "Atrof-muhit va Barqarorlik",
    nameUz: "Atrof-muhit va Barqarorlik",
    nameEn: "Environment & Sustainability",
    emoji: "🌿",
    color: "emerald",
    gradient: "from-emerald-500 to-green-600",
    bgLight: "bg-emerald-50/80",
    borderLight: "border-emerald-200",
    textAccent: "text-emerald-800",
    description: "Barqaror rivojlanish, uglerod neytralligi va global ekologik maqsadlar.",
  },
  "Xalqaro Munosabatlar": {
    category: "Xalqaro Munosabatlar",
    nameUz: "Xalqaro Munosabatlar",
    nameEn: "Global & International Affairs",
    emoji: "🌍",
    color: "sky",
    gradient: "from-sky-500 to-blue-600",
    bgLight: "bg-sky-50/80",
    borderLight: "border-sky-200",
    textAccent: "text-sky-800",
    description: "Geosiyosat, ko‘p tomonlama shartnomalar, xalqaro xavfsizlik va diplomatiya.",
  },
  "Global & International Affairs": {
    category: "Xalqaro Munosabatlar",
    nameUz: "Xalqaro Munosabatlar",
    nameEn: "Global & International Affairs",
    emoji: "🌍",
    color: "sky",
    gradient: "from-sky-500 to-blue-600",
    bgLight: "bg-sky-50/80",
    borderLight: "border-sky-200",
    textAccent: "text-sky-800",
    description: "Geosiyosat, ko‘p tomonlama shartnomalar, xalqaro xavfsizlik va diplomatiya.",
  },
  "Ilg‘or Akademik Leksika": {
    category: "Ilg‘or Akademik Leksika",
    nameUz: "Ilg‘or Akademik Leksika",
    nameEn: "Advanced Academic Lexis",
    emoji: "📜",
    color: "violet",
    gradient: "from-violet-600 to-purple-700",
    bgLight: "bg-violet-50/80",
    borderLight: "border-violet-200",
    textAccent: "text-violet-800",
    description: "IELTS 7.5–8.5, ilmiy jurnallar va akademik maqolalar uchun yuksak leksika.",
  },
  "Advanced Academic Lexis": {
    category: "Ilg‘or Akademik Leksika",
    nameUz: "Ilg‘or Akademik Leksika",
    nameEn: "Advanced Academic Lexis",
    emoji: "📜",
    color: "violet",
    gradient: "from-violet-600 to-purple-700",
    bgLight: "bg-violet-50/80",
    borderLight: "border-violet-200",
    textAccent: "text-violet-800",
    description: "IELTS 7.5–8.5, ilmiy jurnallar va akademik maqolalar uchun yuksak leksika.",
  },
  "Mukammal va Nodir Leksika": {
    category: "Mukammal va Nodir Leksika",
    nameUz: "Mukammal va Nodir Leksika",
    nameEn: "Mastery & Rare Lexis",
    emoji: "💎",
    color: "amber",
    gradient: "from-amber-500 to-rose-600",
    bgLight: "bg-amber-50/80",
    borderLight: "border-amber-200",
    textAccent: "text-amber-900",
    description: "C2 darajasidagi boy ona tili saviyasi, nozik ma’nodosh va nodir adabiy so‘zlar.",
  },
  "Mastery & Rare Lexis": {
    category: "Mukammal va Nodir Leksika",
    nameUz: "Mukammal va Nodir Leksika",
    nameEn: "Mastery & Rare Lexis",
    emoji: "💎",
    color: "amber",
    gradient: "from-amber-500 to-rose-600",
    bgLight: "bg-amber-50/80",
    borderLight: "border-amber-200",
    textAccent: "text-amber-900",
    description: "C2 darajasidagi boy ona tili saviyasi, nozik ma’nodosh va nodir adabiy so‘zlar.",
  },
};

export const CEFR_LEVELS_SEQUENCE: CEFRLevel[] = ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'];

export const CEFR_TOPIC_ORDER: string[] = Object.keys(CEFR_TOPIC_CATEGORIES);

export interface CefrTopicGroup {
  id: string; // topicId (e.g. cefr_a1_greetings)
  category: string; // category string
  nameUz: string;
  nameEn: string;
  emoji: string;
  color: string;
  gradient: string;
  bgLight: string;
  borderLight: string;
  textAccent: string;
  description: string;
  totalWords: number;
  words: Word[];
  learnedCount: number;
  learningCount: number;
  newCount: number;
  percent: number;
}

export function getNextTopicInLevel(
  currentTopicId: string,
  levelTopics: CefrTopicGroup[]
): { nextTopic: CefrTopicGroup | null; isLastTopic: boolean } {
  const index = levelTopics.findIndex(
    (t) => t.id === currentTopicId || t.category === currentTopicId
  );
  if (index === -1) {
    return { nextTopic: null, isLastTopic: false };
  }
  if (index + 1 < levelTopics.length) {
    return { nextTopic: levelTopics[index + 1], isLastTopic: false };
  }
  return { nextTopic: null, isLastTopic: true };
}

export function getNextCefrLevel(currentLevel: CEFRLevel): CEFRLevel | null {
  const idx = CEFR_LEVELS_SEQUENCE.indexOf(currentLevel);
  if (idx !== -1 && idx + 1 < CEFR_LEVELS_SEQUENCE.length) {
    return CEFR_LEVELS_SEQUENCE[idx + 1];
  }
  return null;
}

export function groupCefrWordsByTopic(
  words: Word[],
  wordProgress: Record<string, any> = {}
): CefrTopicGroup[] {
  const map = new Map<string, Word[]>();

  for (const w of words) {
    const cat = w.category || 'Salomlashuv va Kundalik muloqot';
    if (!map.has(cat)) {
      map.set(cat, []);
    }
    map.get(cat)!.push(w);
  }

  const groups: CefrTopicGroup[] = [];

  for (const [cat, catWords] of map.entries()) {
    const meta = CEFR_TOPIC_CATEGORIES[cat] || {
      category: cat,
      nameUz: cat,
      nameEn: catWords[0]?.topicId?.replace(/^cefr_[a-z0-9]+_/, '') || 'Topic Words',
      emoji: '📚',
      color: 'indigo',
      gradient: 'from-indigo-600 to-blue-700',
      bgLight: 'bg-indigo-50/80',
      borderLight: 'border-indigo-200',
      textAccent: 'text-indigo-800',
      description: `${cat} mavzusiga oid saralangan leksika va iboralar to‘plami.`,
    };

    let learnedCount = 0;
    let learningCount = 0;

    for (const w of catWords) {
      const p = wordProgress[w.id];
      if (p) {
        if (p.masteryLevel === 'ozlashtirilgan') learnedCount++;
        else if (p.masteryLevel === 'organilmoqda') learningCount++;
      }
    }

    const totalWords = catWords.length;
    const newCount = Math.max(0, totalWords - learnedCount - learningCount);
    const weightedLearned = learnedCount + learningCount * 0.5;
    let percent = 0;
    if (totalWords > 0 && weightedLearned > 0) {
      const calc = (weightedLearned / totalWords) * 100;
      percent = calc < 1 ? Math.max(0.1, Number(calc.toFixed(1))) : Math.round(calc);
    }
    const topicId = catWords[0]?.topicId || `cefr_topic_${encodeURIComponent(cat)}`;

    groups.push({
      id: topicId,
      category: cat,
      nameUz: meta.nameUz,
      nameEn: meta.nameEn,
      emoji: meta.emoji,
      color: meta.color,
      gradient: meta.gradient,
      bgLight: meta.bgLight,
      borderLight: meta.borderLight,
      textAccent: meta.textAccent,
      description: meta.description,
      totalWords,
      words: catWords,
      learnedCount,
      learningCount,
      newCount,
      percent,
    });
  }

  // Sort groups strictly by their natural appearance order in the dataset (first word's orderNumber)
  return groups.sort((a, b) => {
    const firstA = a.words[0]?.orderNumber || 0;
    const firstB = b.words[0]?.orderNumber || 0;
    return firstA - firstB;
  });
}

export const TOTAL_CEFR_WORDS = 10000;

// In-memory cache for level words
const wordsCache = new Map<CEFRLevel, Word[]>();
let starterWordsCache: Word[] | null = null;

/**
 * Load all words for a specific CEFR level (A1=1500, A2=1500, B1=2000, B2=2500, C1=1500, C2=1000)
 */
export async function getCefrLevelWords(level: CEFRLevel): Promise<Word[]> {
  if (wordsCache.has(level)) {
    return wordsCache.get(level)!;
  }

  try {
    const res = await fetch(`/data/cefr/${level.toLowerCase()}.json?v=${CEFR_DATABASE_VERSION}`);
    if (!res.ok) {
      throw new Error(`Failed to load CEFR ${level} vocabulary: ${res.statusText}`);
    }
    const data: Word[] = await res.json();
    wordsCache.set(level, data);
    saveCefrLevelOffline(level, data).catch(() => {});
    return data;
  } catch (err) {
    console.warn(`[Verbo Offline] Network fetch failed for CEFR ${level}, checking offline cache:`, err);
    const offlineCached = await getCefrLevelOffline(level);
    if (offlineCached && offlineCached.length > 0) {
      wordsCache.set(level, offlineCached);
      return offlineCached;
    }
    const starters = await getCefrStarterWords();
    const fallback = starters.filter((w) => w.level === level);
    return fallback;
  }
}

/**
 * Load quick preview starter words
 */
export async function getCefrStarterWords(): Promise<Word[]> {
  if (starterWordsCache) {
    return starterWordsCache;
  }

  try {
    const res = await fetch(`/data/cefr/starter_preview.json?v=${CEFR_DATABASE_VERSION}`);
    if (res.ok) {
      const data: Word[] = await res.json();
      starterWordsCache = data;
      return data;
    }
  } catch (err) {
    console.warn('Could not load starter preview words:', err);
  }

  return [];
}

export function clearCefrCache(): void {
  wordsCache.clear();
  starterWordsCache = null;
}
