#!/usr/bin/env python3
import json, re

# Complete dictionary of all user-specified disambiguations and updated translations
DISAMBIGUATIONS = {
    # Level A1
    ('A1', 'answer'): "javob (javob)",
    ('A1', 'false'): "noto‘g‘ri (soxta, xato)",
    ('A1', 'fine, thanks'): "yaxshi, rahmat",
    ('A1', 'idea'): "g‘oya (g'oya)",
    ('A1', 'problem'): "muammo (muammo)",
    ('A1', 'question'): "savol (savol)",
    ('A1', 'reply'): "javob bermoq (javob bermoq (xat/xabarga))",
    ('A1', 'right'): "to‘g‘ri (to'g'ri, o'ng)",
    ('A1', 'say'): "aytmoq (demoq, gapirmoq (so'zlarni keltirish))",
    ('A1', 'speak'): "gapirmoq (gapirmoq (rasmiyroq yoki bir tomonlama))",
    ('A1', 'sure'): "albatta / mayli (ishonchli, aniq)",
    ('A1', 'tell'): "aytib bermoq (aytmoq, hikoya qilmoq (kimgadir ma'lumot berish))",
    ('A1', 'true'): "to‘g‘ri (haqiqiy)",
    ('A1', 'understand'): "tushunmoq (tushunmoq)",
    ('A1', 'wrong'): "noto‘g‘ri (noto'g'ri, xato)",
    ('A1', 'arrive'): "yetib kelmoq (yetib kelmoq)",
    ('A1', 'journey'): "sayohat (uzoq masofali sayohat)",
    ('A1', 'leave'): "ketmoq (tark etmoq, chiqib ketmoq)",
    ('A1', 'travel'): "sayohat qilmoq (umumiy sayohat qilish jarayoni)",
    ('A1', 'trip'): "sayohat (sayohat, qisqa safar)",
    ('A1', 'believe'): "ishonmoq (ishonmoq)",
    ('A1', 'bring'): "olib kelmoq (olib kelmoq)",
    ('A1', 'carry'): "olib yurmoq (tashimoq, ko'tarib yurmoq)",
    ('A1', 'fight'): "jang qilmoq (urishmoq, kurashmoq)",
    ('A1', 'fly'): "uchmoq (uchmoq)",
    ('A1', 'get'): "olmoq/ega bo‘lmoq (olmoq, erishmoq)",
    ('A1', 'hear'): "eshitmoq (eshitmoq (tabiiy qobiliyat))",
    ('A1', 'hold'): "ushlamoq (ushlab turmoq)",
    ('A1', 'hope'): "umid qilmoq (umid qilmoq)",
    ('A1', 'know'): "bilmoq (bilmoq)",
    ('A1', 'like'): "yoqtirmoq (yoqtirmoq)",
    ('A1', 'love'): "sevmoq (sevmoq)",
    ('A1', 'need'): "kerak bo‘lmoq (muhtoj bo'lmoq, kerak bo'lmoq)",
    ('A1', 'play'): "o‘ynamoq (o'ynamoq, cholg'uda ijro etmoq)",
    ('A1', 'pull'): "tortmoq (tortmoq)",
    ('A1', 'push'): "itarmoq (itarmoq)",
    ('A1', 'put'): "qo'ymoq (qo'ymoq)",
    ('A1', 'see'): "ko‘rmoq (ko'rmoq (tabiiy qobiliyat))",
    ('A1', 'spend'): "sarflamoq (sarflamoq (vaqt yoki pul))",
    ('A1', 'stop'): "to‘xtamoq (to'xtatmoq, to'xtamoq)",
    ('A1', 'swim'): "suzmoq (suzmoq)",
    ('A1', 'take'): "olmoq (olmoq (olib ketmoq))",
    ('A1', 'talk'): "suhbatlashmoq (suhbatlashmoq (muloqot, ikki tomonlama))",
    ('A1', 'teach'): "o‘qitmoq (o'rgatmoq)",
    ('A1', 'think'): "o‘ylamoq (o'ylamoq)",
    ('A1', 'want'): "xohlamoq (xohlamoq)",
    ('A1', 'angry'): "jahli chiqqan (jahli chiqqan)",
    ('A1', 'bored'): "zerikkan (zerikkan)",
    ('A1', 'common'): "umumiy / keng tarqalgan (umumiy, odatiy)",
    ('A1', 'dangerous'): "xavfli (xavfli)",
    ('A1', 'fast'): "tez (tez)",
    ('A1', 'funny'): "kulgili (kulgili)",
    ('A1', 'happy'): "xursand (baxtli)",
    ('A1', 'hard'): "qiyin/qattiq (qattiq, qiyin)",
    ('A1', 'heavy'): "og'ir (og'ir)",
    ('A1', 'high'): "yuqori (baland (yer sathidan uzoqda))",
    ('A1', 'important'): "muhim (muhim)",
    ('A1', 'impossible'): "imkonsiz (imkonsiz)",
    ('A1', 'interesting'): "qiziqarli (qiziqarli)",
    ('A1', 'modern'): "zamonaviy (zamonaviy)",
    ('A1', 'normal'): "oddiy (normal, tabiiy)",
    ('A1', 'poor'): "kambag'al (kambag'al, nochor)",
    ('A1', 'possible'): "mumkin (mumkin)",
    ('A1', 'private'): "shaxsiy (shaxsiy)",
    ('A1', 'public'): "ommaviy (jamoatchilik)",
    ('A1', 'quiet'): "jim / sokin (sokin, tinch)",
    ('A1', 'real'): "haqiqiy (haqiqiy)",
    ('A1', 'rich'): "boy (badavlat, boy (pulga nisbatan))",
    ('A1', 'sad'): "xafa (g'amgin)",
    ('A1', 'safe'): "xavfsiz (xavfsiz)",
    ('A1', 'serious'): "jiddiy (jiddiy)",
    ('A1', 'slow'): "sekin (sekin)",
    ('A1', 'special'): "maxsus (maxsus)",
    ('A1', 'tall'): "baland/bo‘yi uzun (bo'yli baland (odam yoki binolarga nisbatan))",
    ('A1', 'traditional'): "an'anaviy (an'anaviy)",
    ('A1', 'always'): "har doim (har doim)",
    ('A1', 'never'): "hech qachon (hech qachon)",
    ('A1', 'age'): "yosh (yosh)",
    ('A1', 'baby'): "chaqaloq (go'dak, chaqaloq)",
    ('A1', 'child'): "bola (bola (umumiy))",
    ('A1', 'doctor'): "shifokor (shifokor)",
    ('A1', 'girl'): "qiz (qiz bola)",
    ('A1', 'man'): "erkak (erkak)",
    ('A1', 'nurse'): "hamshira (hamshira)",
    ('A1', 'people'): "odamlar (odamlar (ko'plik))",
    ('A1', 'person'): "odam (shaxs (birlik))",
    ('A1', 'student'): "talaba/o‘quvchi (talaba, o'quvchi)",
    ('A1', 'teacher'): "o‘qituvchi (o'qituvchi)",
    ('A1', 'woman'): "ayol (ayol)",
    ('A1', 'class'): "sinf/guruh (sinf, dars)",
    ('A1', 'home'): "uy (uy, o'choq (yashaydigan maskan, qadrdon joy))",
    ('A1', 'job'): "kasb/ish (ish, vazifa (kundalik))",
    ('A1', 'old'): "qari/eski (eski, qari)",
    ('A1', 'place'): "joy (joylashtirmoq, joy)",
    ('A1', 'road'): "yo‘l (yo'l (avtomobil uchun))",
    ('A1', 'school'): "maktab (maktab)",
    ('A1', 'street'): "ko‘cha (ko'cha (shahardagi))",
    ('A1', 'study'): "o‘qimoq (o'rganmoq, o'qimoq)",
    ('A1', 'university'): "universitet (universitet)",
    ('A1', 'work'): "ishlamoq (mehnat, ish faoliyati)",
    ('A1', 'young'): "yosh (yosh)",
    ('A1', 'early'): "erta (erta)",
    ('A1', 'first'): "birinchi (birinchi)",
    ('A1', 'future'): "kelajak (kelajak)",
    ('A1', 'last'): "oxirgi (oxirgi)",
    ('A1', 'late'): "kech (kech)",
    ('A1', 'now'): "hozir (hozir)",
    ('A1', 'often'): "tez-tez (tez-tez)",
    ('A1', 'past'): "o'tmish (o'tgan)",
    ('A1', 'period'): "davr (davr)",
    ('A1', 'sometimes'): "ba'zan (ba'zida)",
    ('A1', 'soon'): "tez orada (tez orada)",
    ('A1', 'suddenly'): "to'satdan (to'satdan)",
    ('A1', 'time'): "vaqt (vaqt)",
    ('A1', 'usually'): "odatda (odatda)",
    ('A1', 'year'): "yil (yil)",
    ('A1', 'apartment'): "kvartira (kvartira (American))",
    ('A1', 'flat'): "kvartira (kvartira (British))",
    ('A1', 'house'): "uy (uy (binoning o'zi))",
    ('A1', 'light'): "chiroq/yorug‘lik (engil, yorug')",
    ('A1', 'bad'): "yomon (yomon)",
    ('A1', 'good'): "yaxshi (yaxshi)",
    ('A1', 'college'): "kollej (kollej)",
    ('A1', 'difficult'): "qiyin (qiyin)",
    ('A1', 'easy'): "oson (oson)",
    ('A1', 'finish'): "tugatmoq (tamomlamoq, tugatmoq (ishni oxiriga yetkazish))",
    ('A1', 'learn'): "o‘rganmoq (o'rganmoq (yangi ko'nikma))",
    ('A1', 'listen'): "tinglamoq (tinglamoq (diqqat bilan))",
    ('A1', 'music'): "musiqa (musiqa)",
    ('A1', 'sport'): "sport (sport)",
    ('A1', 'start'): "boshlamoq (boshlamoq)",
    ('A1', 'beautiful'): "chiroyli (general: tabiat, ayollar, manzara uchun)",
    ('A1', 'big'): "katta (general: umumiy katta hajm uchun)",
    ('A1', 'clean'): "toza (toza)",
    ('A1', 'handsome'): "kelishgan (erkaklarga nisbatan chiroyli/kelishgan)",
    ('A1', 'look'): "ko‘rinmoq/qaramoq (qaramoq (ongli harakat))",
    ('A1', 'new'): "yangi (yangi)",
    ('A1', 'small'): "kichik (general: kichik)",
    ('A1', 'watch'): "qo‘l soati (kuzatmoq, tomosha qilmoq (harakatda))",
    ('A1', 'brain'): "miya (miya (organ))",
    ('A1', 'clinic'): "poliklinika (klinika)",
    ('A1', 'disease'): "kasallik (kasallik)",
    ('A1', 'feel'): "his qilmoq (sezmoq, his qilmoq)",
    ('A1', 'health'): "sog‘liq (sog'liq)",
    ('A1', 'hospital'): "kasalxona (shifoxona)",
    ('A1', 'hurt'): "og‘rimoq (og'ritmoq)",
    ('A1', 'ill'): "kasal (kasal, xasta (rasmiyroq))",
    ('A1', 'medicine'): "dori (dori, tibbiyot)",
    ('A1', 'pain'): "og‘riq (og'riq)",
    ('A1', 'run'): "yugurmoq (yugurmoq, boshqarmoq (biznesni))",
    ('A1', 'sick'): "kasal (betob, ko'ngli aynigan)",

    # Level A2
    ('A2', 'arrive'): "yetib kelmoq (yetib kelmoq)",
    ('A2', 'fly'): "uchmoq (uchmoq)",
    ('A2', 'journey'): "sayohat (uzoq masofali sayohat)",
    ('A2', 'road'): "yo'l (yo'l (avtomobil uchun))",
    ('A2', 'trip'): "safar (sayohat, qisqa safar)",
    ('A2', 'career'): "karyera (karyera, kasbiy yo'l)",
    ('A2', 'shift'): "smena (siljitmoq, o'rin almashtirmoq)",
    ('A2', 'obvious'): "aniq / ravshan (yaqqol, aniq)",
    ('A2', 'cost'): "narxi bo'lmoq (turmoq (narxga ega bo'lmoq))",
    ('A2', 'win'): "yutmoq (yutmoq (musobaqa, o'yin))",
    ('A2', 'ancient'): "qadimiy (qadimiy)",
    ('A2', 'habit'): "odat (odat)",
    ('A2', 'rarely'): "kamdan-kam (kamdan-kam)",

    # Level B1
    ('B1', 'brain'): "miya (miya (organ))",
    ('B1', 'damage'): "zarar yetkazmoq, zarar (zarar yetkazmoq)",
    ('B1', 'disease'): "kasallik (kasallik)",
    ('B1', 'health'): "sog'liq (sog'liq)",
    ('B1', 'hospital'): "shifoxona (shifoxona)",
    ('B1', 'hurt'): "og'rimoq, jarohatlamoq (og'ritmoq)",
    ('B1', 'ill'): "kasal (kasal, xasta (rasmiyroq))",
    ('B1', 'illness'): "kasallik (xastalik)",
    ('B1', 'medicine'): "dori (dori, tibbiyot)",
    ('B1', 'nurse'): "hamshira (hamshira)",
    ('B1', 'pain'): "og'riq (og'riq)",
    ('B1', 'click'): "bosmoq (sichqonchani)",
    ('B1', 'career'): "karyera (karyera, kasbiy yo'l)",
    ('B1', 'doctor'): "shifokor (shifokor)",
    ('B1', 'match'): "mos tushmoq (match, o'yin)",
    ('B1', 'culture'): "madaniyat (madaniyat)",
    ('B1', 'dance'): "raqs, raqsga tushmoq (raqs tushmoq)",
    ('B1', 'play'): "spektakl, o'ynamoq (o'ynamoq, cholg'uda ijro etmoq)",
    ('B1', 'custom'): "urf-odat (urf-odat)",
    ('B1', 'peace'): "tinchlik (tinchlik)",
    ('B1', 'public'): "ommaviy, jamoatchilik (jamoatchilik)",
    ('B1', 'society'): "jamiyat (jamiyat)",
    ('B1', 'arrive'): "yetib kelmoq (yetib kelmoq)",
    ('B1', 'beat'): "urmoq, yengmoq (urmoq, kaltaklamoq)",
    ('B1', 'begin'): "boshlamoq (boshlamoq (rasmiyroq))",
    ('B1', 'believe'): "ishonmoq (ishonmoq)",
    ('B1', 'bring'): "olib kelmoq (olib kelmoq)",
    ('B1', 'buy'): "sotib olmoq (sotib olmoq)",
    ('B1', 'carry'): "tashimoq, ko'tarib yurmoq (tashimoq, ko'tarib yurmoq)",
    ('B1', 'change'): "o'zgartirmoq (o'zgartirmoq, almashtirmoq)",
    ('B1', 'clean'): "tozalamoq (toza)",
    ('B1', 'clear'): "bo'shatmoq, tozalamoq (tiniq, tushunarli)",
    ('B1', 'climb'): "tirmashib chiqmoq (tirmashib chiqmoq)",
    ('B1', 'drop'): "tushirib yubormoq, tushmoq (tushirib yubormoq)",
    ('B1', 'quiet'): "yuvosh, sokin (sokin, tinch)",
    ('B1', 'serious'): "jiddiy (jiddiy)",
    ('B1', 'earn'): "pul ishlamoq (pul ishlab topmoq)",
    ('B1', 'pay'): "to'lamoq (to'lamoq)",
    ('B1', 'spend'): "sarflamoq (sarflamoq (vaqt yoki pul))",
    ('B1', 'path'): "so'qmoq (so'qmoq, yo'lak)",
    ('B1', 'answer'): "javob bermoq, javob (javob)",
    ('B1', 'mind'): "qarshi bo'lmoq (aql, ong)",
    ('B1', 'reply'): "javob qaytarmoq (javob bermoq (xat/xabarga))",
    ('B1', 'understand'): "tushunmoq (tushunmoq)",
    ('B1', 'depart'): "jo'nab ketmoq (jo'nab ketmoq (transport))",
    ('B1', 'fly'): "uchmoq (uchmoq)",
    ('B1', 'journey'): "sayohat (uzoq masofali sayohat)",
    ('B1', 'road'): "yo'l (yo'l (avtomobil uchun))",
    ('B1', 'stop'): "bekat, to'xtash (to'xtatmoq, to'xtamoq)",
    ('B1', 'street'): "ko'cha (ko'cha (shahardagi))",
    ('B1', 'tour'): "tur, sayohat (ekskursiya, turistik safar)",
    ('B1', 'travel'): "sayohat qilmoq (umumiy sayohat qilish jarayoni)",
    ('B1', 'trip'): "safar, qisqa sayohat (sayohat, qisqa safar)",
    ('B1', 'walk'): "yurmoq, sayr (yurmoq, sayr qilmoq)",
    ('B1', 'way'): "yo'l, usul (yo'l, usul)",
    ('B1', 'apartment'): "kvartira (kvartira (American))",
    ('B1', 'purchase'): "xarid, sotib olmoq (xarid qilmoq (rasmiyroq))",
    ('B1', 'professor'): "professor (professor)",

    # Level B2
    ('B2', 'community'): "jamiyat, hamjamiyat (jamoa)",
    ('B2', 'right'): "huquq (to'g'ri, o'ng)",
    ('B2', 'scandal'): "janjal, mashmash (skandal)",
    ('B2', 'society'): "jamiyat (jamiyat)",
    ('B2', 'career'): "karyera (karyera, kasbiy yo'l)",
    ('B2', 'purchase'): "xarid / xarid qilmoq (xarid qilmoq (rasmiyroq))",
    ('B2', 'college'): "kollej (kollej)",
    ('B2', 'primary'): "boshlang'ich (birlamchi, asosiy)",
    ('B2', 'professor'): "professor (professor)",
    ('B2', 'pupil'): "o'quvchi (o'quvchi (maktab))",
    ('B2', 'student'): "talaba (talaba, o'quvchi)",
    ('B2', 'university'): "universitet (universitet)",
    ('B2', 'anger'): "g'azab (g'azab)",
    ('B2', 'culture'): "madaniyat (madaniyat)",
    ('B2', 'danger'): "xavf (xavf)",
    ('B2', 'difficulty'): "qiyinchilik (qiyinchilik)",
    ('B2', 'disease'): "kasallik (kasallik)",
    ('B2', 'fear'): "qo'rquv (qo'rqmoq)",
    ('B2', 'future'): "kelajak (kelajak)",
    ('B2', 'habit'): "odat (odat)",
    ('B2', 'health'): "sog'liq (sog'liq)",
    ('B2', 'hope'): "umid (umid qilmoq)",
    ('B2', 'idea'): "g'oya (g'oya)",
    ('B2', 'issue'): "masala, muammo (masala, muhokama qilinadigan mavzu)",
    ('B2', 'love'): "muhabbat (sevmoq)",
    ('B2', 'mind'): "aql, ong (aql, ong)",
    ('B2', 'need'): "ehtiyoj (muhtoj bo'lmoq, kerak bo'lmoq)",
    ('B2', 'opinion'): "fikr (shaxsiy fikr, qarash)",
    ('B2', 'pain'): "og'riq (og'riq)",
    ('B2', 'peace'): "tinchlik (tinchlik)",
    ('B2', 'period'): "davr (davr)",
    ('B2', 'person'): "shaxs (shaxs (birlik))",
    ('B2', 'place'): "joy (joylashtirmoq, joy)",
    ('B2', 'problem'): "muammo (muammo)",
    ('B2', 'question'): "savol (savol)",
    ('B2', 'response'): "javob (reaksiya, javob)",
    ('B2', 'risk'): "tavakkal, xavf (xavf)",
    ('B2', 'thought'): "fikr (fikr, xayol)",
    ('B2', 'time'): "vaqt (vaqt)",
    ('B2', 'voice'): "ovoz (ovoz (odamniki))",
    ('B2', 'way'): "yo'l (yo'l, usul)",
    ('B2', 'wish'): "tilak, istak (istamoq, tilamoq)",
    ('B2', 'work'): "ish (mehnat, ish faoliyati)",
    ('B2', 'alter'): "o'zgartirmoq (o'zgartirmoq (tuzilishini))",
    ('B2', 'earn'): "pul ishlab topmoq (pul ishlab topmoq)",
    ('B2', 'match'): "mos tushmoq (match, o'yin)",
    ('B2', 'modify'): "o'zgartirmoq (takomillashtirmoq, o'zgartirmoq)",
    ('B2', 'reply'): "javob bermoq (javob bermoq (xat/xabarga))",
    ('B2', 'secure'): "xavfsiz qilmoq (himoyalangan)",
    ('B2', 'shift'): "siljitmoq (siljitmoq, o'rin almashtirmoq)",
    ('B2', 'understand'): "tushunmoq (tushunmoq)",

    # Level C1
    ('C1', 'issue'): "masala (masala, muhokama qilinadigan mavzu)",
    ('C1', 'job'): "ish (ish, vazifa (kundalik))",
    ('C1', 'major'): "asosiy (katta, asosiy)",
    ('C1', 'minor'): "kichik, ahamiyatsiz (kichik, ahamiyatsiz)",
    ('C1', 'modify'): "o'zgartirmoq (takomillashtirmoq, o'zgartirmoq)",
    ('C1', 'obvious'): "aniq, yaqqol (yaqqol, aniq)",
    ('C1', 'period'): "davr (davr)",
    ('C1', 'previous'): "oldingi (oldingi)",
    ('C1', 'primary'): "asosiy (birlamchi, asosiy)",
    ('C1', 'purchase'): "sotib olmoq (xarid qilmoq (rasmiyroq))",
    ('C1', 'secure'): "xavfsiz (himoyalangan)",
    ('C1', 'shift'): "siljitmoq (siljitmoq, o'rin almashtirmoq)",
    ('C1', 'specific'): "aniq, o'ziga xos (aniq, o'ziga xos)",
    ('C1', 'team'): "jamoa (jamoa)",
}

total_updated = 0
for lvl in ['a1', 'a2', 'b1', 'b2', 'c1', 'c2']:
    fp = f"public/data/cefr/{lvl}.json"
    with open(fp, 'r', encoding='utf-8') as f:
        words = json.load(f)
    
    lvl_upper = lvl.upper()
    modified = 0
    for w in words:
        clean_eng = w['english'].strip().lower()
        key = (lvl_upper, clean_eng)
        if key in DISAMBIGUATIONS:
            new_uz = DISAMBIGUATIONS[key]
            if w['uzbek'] != new_uz:
                w['uzbek'] = new_uz
                modified += 1
                total_updated += 1
                
    with open(fp, 'w', encoding='utf-8') as f:
        json.dump(words, f, ensure_ascii=False, indent=2)
    print(f"Level {lvl_upper}: updated {modified} words in {fp}")

# Also update starter_preview.json
starter_file = "public/data/cefr/starter_preview.json"
with open(starter_file, 'r', encoding='utf-8') as f:
    starters = json.load(f)

for w in starters:
    lvl_upper = w['level']
    clean_eng = w['english'].strip().lower()
    key = (lvl_upper, clean_eng)
    if key in DISAMBIGUATIONS:
        w['uzbek'] = DISAMBIGUATIONS[key]

with open(starter_file, 'w', encoding='utf-8') as f:
    json.dump(starters, f, ensure_ascii=False, indent=2)

print(f"Total updated across database: {total_updated}")
print("Starter preview updated!")
